### ISSUE TITLE
SQL is not being rendered in BaseSQLDecoratedOperator

### ISSUE THREAD

**Issue by feluelle** [astronomer/astro-sdk#1003]
As a user I would like to see the rendered sql in the task instance "Rendered" section of the Airflow UI.

cc @mikeshwe (as, if I am not mistaken, you brought this up)

**Comment by sunank200** [comment]
We need to verify this. @feluelle is this already fixed?

**Comment by feluelle** [comment]
No, the PR for that is still in Draft.
