### ISSUE TITLE
Add Config and Table params in run.sh script

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#1009]
**Please describe the feature you'd like to see**
Currently, 
1. We are passing the benchmarking table via the env variable.
2. The config used for benchmarking is hardcoded in the code. 

**Describe the solution you'd like**
We can add parameters in `run.sh` to accept config and table.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by sunank200** [comment]
This is not required anymore
