### ISSUE TITLE
Uncomment kube pod teardown

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#1011]
**Please describe the feature you'd like to see**
We have commented in python-sdk/tests/benchmark/wait_for_completion.sh
#kubectl delete job benchmark-"${GIT_HASH}" -n benchmark

This is done until we stabilize the benchmarking we need to look at logs.

**Describe the solution you'd like**
We need to uncomment it once we stabilize the benchmarking

**Comment by sunank200** [comment]
This is old ticket not relevant any more

**Comment by pankajastro** [comment]
this has yet not done PR https://github.com/astronomer/astro-sdk/pull/1623
