### ISSUE TITLE
[Benchmark] Modify run.sh to accept config as param

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#1019]
**Please describe the feature you'd like to see**
We use config path which is currently hardcoded in the codebase. Since we want to run different configs for CI, Weekly jobs we cannot do it right now.

**Describe the solution you'd like**
We need to modify the CI to accept the config to run benchmarks on as a param.

**Are there any alternatives to this feature?**
Is there another way we could solve this problem or enable this use-case?

**Additional context**
Add any other context about the feature request here.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by sunank200** [comment]
This is not required anymore
