### ISSUE TITLE
Test Migration path for Python SDK 1.1 to 1.2

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#1046]
We should test that users who enabled pickling are able to upgrade to Python SDK 1.2 from Python SDK 1.1 with a) pickling enabled and b) using Astro SDK Custom XCom backend built in https://github.com/astronomer/astro-sdk/pull/970

A good test would be install Astro SDK 1.1 and run some example dags and then upgrade python SDK to 1.2 and run the same DAGs. Check whether you can access XCom view in the Webserver too. Next test should be to disable pickling and use our Custom XCom backend and repeat the test

**Comment by kaxil** [comment]
Also looks like we don't have any docs about setting Custom XCom backend in https://astro-sdk-python.readthedocs.io/en/latest/index.html  unless we add https://github.com/astronomer/astro-sdk/pull/1036 ?

**Comment by phanikumv** [comment]
Getting the below error when I  disable XCOM pickling, and execute my DAG using the latest code base on main branch. I did enable the custom xcom backend with
`AIRFLOW__CORE__XCOM_BACKEND: astro.custom_backend.astro_custom_backend.AstroCustomXcomBackend
`
Am I missing something here?

cc @dimberman 

```
[2022-10-12, 13:17:26 UTC] {xcom.py:599} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-10-12, 13:17:26 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2378, in xcom_push
    XCom.set(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/xcom.py", line 206, in set
    value = cls.serialize_value(
  File "/usr/local/lib/python3.9/site-packages/airflow/models/xcom.py", line 597, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Table is not JSON serializable
```

**Comment by phanikumv** [comment]
Test results by disabling pickling.

```
**Env variables**
AIRFLOW__CORE__XCOM_BACKEND: astro.custom_backend.astro_custom_backend.AstroCustomXcomBackend
AIRFLOW__ASTRO_SDK__XCOM_STORAGE_CONN_ID: aws_s3_default
AIRFLOW__ASTRO_SDK__XCOM_STORAGE_URL: s3://xcombucket/xcomfolder/

**Task**
load_table_with_data = aql.load_file(
        input_file=File(path=f"{S3_BUCKET_NAME_SOURCE}/crxbank1.csv",
                        filetype=FileType.CSV, conn_id=AWS_CONN_ID),
        task_id="load_csv_data_bank1",
        outlets=[Dataset("snowflake://crx_data_bank1")],
        do_xcom_push=True
)

**Result**
The dataframe got saved successfully in s3.

<img width="1423" alt="Screenshot 2022-10-14 at 7 28 04 PM" src="https://user-images.githubusercontent.com/94376113/195893133-b4d5f844-58c5-43af-8dc7-a4b31d5bb16c.png">




    
```

**Comment by kaxil** [comment]
**Scenario**:

- Install SDK 1.1.1, run `example_dag` with `load_file` -- and it should succeed (with XCom pickling)
- Upgrade to the code in the main branch, and you clear the task that succeeded previously

Verify this by checking that the Task Run history on the UI is visible.

My fear is that if you visit Admin -> Xcom page might blow up. Will be good to test it out

**Comment by phanikumv** [comment]
> **Scenario**:
> 
> * Install SDK 1.1.1, run `example_dag` with `load_file` -- and it should succeed (with XCom pickling)
> * Upgrade to the code in the main branch, and you clear the task that succeeded previously
> 
> Verify this by checking that the Task Run history on the UI is visible.
> 
> My fear is that if you visit Admin -> Xcom page might blow up. Will be good to test it out

This scenario works. Please find the results for each of the scenario below @kaxil .

**SDK 1.1.1 with Xcom picking enabled**
<img width="1658" alt="Screenshot 2022-10-17 at 8 47 52 PM" src="https://user-images.githubusercontent.com/94376113/196223601-924682e9-1318-469b-8ea7-6d1d4ef44e84.png">

**Upgrade code to current main branch with Xcom picking enabled, restarted containers(using `make stop` and `make build-run`) and cleared the task**
<img width="1670" alt="Screenshot 2022-10-17 at 9 04 47 PM" src="https://user-images.githubusercontent.com/94376113/196223968-8ce4064c-bb55-42aa-8542-2894aad0b418.png">

**Used code from current main branch, with Xcom picking disabled, custom Xcom enabled, restarted containers(using `make stop` and `make build-run`) and cleared the task**
<img width="1666" alt="Screenshot 2022-10-17 at 9 16 09 PM" src="https://user-images.githubusercontent.com/94376113/196225251-b100ff78-0d64-4fb1-9359-2b6d3556b656.png">

**Comment by phanikumv** [comment]
Closing this as the upgrade scenarios have been tested
