### ISSUE TITLE
Astro CLI should prompt users if there is a newer version of the SQL CLI available

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#1054]
TODO: re-write
**Please describe the feature you'd like to see**
From the moment a SQL project is initialised, we want to ensure all the commands are run using the same version of the SQL CLI.
This means that users may be using an older version of the SQL CLI - while we're implementing new features/

We'd like for the Astro CLI to info SQL CLI users that there is a new version available.

**Describe the solution you'd like**
If a user runs:
```
astro flow validate
```
And the user is using SQL CLI 0.1.0, and we've released 0.1.1, we'd like the Astro CLI to notify the user:
```
Updates are available for the SQL CLI component (0.1.0 is installed, but 0.1.1 is available).  To update it, please run:
$ astro flow update
```

**Are there any alternatives to this feature?**
Not updating dependencies, which would make users use an outdated version.
Always updating the dependency, which could lead to a breaking change.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)

**Comment by kaxil** [comment]
I am happy for us to move this to 0.2.0

**Comment by tatiana** [comment]
Whenever the user is using a "flow" command, we should give users a choice to decide if they want to upgrade or not - telling them the current version and the latest available
