### ISSUE TITLE
Benchmark - load_file() Memory leak

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#1058]
**Describe the bug**
When running benchmarking we are observing a large amount of memory being consumed and not getting free. As a result, we need to use a large machine to run benchmarks.

**Version**
* Astro: 1.1.1

**To Reproduce**
1. Run benchmark
2. log into the pod
3. Observe the memory being consumed/Free memory

**Expected behavior**
Memory consumption should always come down to available memory.

**Comment by sunank200** [comment]
Removing the milestone from 1.2.1
