### ISSUE TITLE
Optimize the table creation for snowflake

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#1097]
**Please describe the feature you'd like to see**
Currently, we are creating the table using - `write_pandas()` function. Which loads the dataframe in the table and then we are truncating. 

We have to use this method because the alternative - prep_table() was not allowing us to control the quotes added.

**Describe the solution you'd like**
No solution yet, we need to find one. But we definitely shouldn't load the data frame while creating a table.

**Comment by sunank200** [comment]
This is done.
