### ISSUE TITLE
SQL CLI commands printing lots of warnings

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#1104]
**Describe the bug**

When @mikeshwe  ran SQL CLI commands on Anaconda, he got lots of warnings:
```
(base) michaelshwe@Michaels-MBP-4 ~ % flow version
/Users/michaelshwe/opt/anaconda3/lib/python3.9/site-packages/airflow/configuration.py:549: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_option_from_config_file(deprecated_key, deprecated_section, key, kwargs, section)
/Users/michaelshwe/opt/anaconda3/lib/python3.9/site-packages/airflow/configuration.py:443: FutureWarning: The 'dag_default_view' setting in [webserver] has the old default value of 'tree'. This value has been changed to 'grid' in the running config, but please update your config before Apache Airflow 3.0.
  warnings.warn(
/Users/michaelshwe/opt/anaconda3/lib/python3.9/site-packages/airflow/configuration.py:443: FutureWarning: The 'log_filename_template' setting in [logging] has the old default value of '{{ ti.dag_id }}/{{ ti.task_id }}/{{ ts }}/{{ try_number }}.log'. This value has been changed to 'dag_id={{ ti.dag_id }}/run_id={{ ti.run_id }}/task_id={{ ti.task_id }}/{% if ti.map_index >= 0 %}map_index={{ ti.map_index }}/{% endif %}attempt={{ try_number }}.log' in the running config, but please update your config before Apache Airflow 3.0.
  warnings.warn(
/Users/michaelshwe/opt/anaconda3/lib/python3.9/site-packages/airflow/configuration.py:549: DeprecationWarning: The auth_backend option in [api] has been renamed to auth_backends - the old setting has been used, but please update your config.
  option = self._get_option_from_config_file(deprecated_key, deprecated_section, key, kwargs, section)
/Users/michaelshwe/opt/anaconda3/lib/python3.9/site-packages/airflow/configuration.py:443: FutureWarning: The 'auth_backends' setting in [api] has the old default value of 'airflow.api.auth.backend.deny_all'. This value has been changed to 'airflow.api.auth.backend.session' in the running config, but please update your config before Apache Airflow 3.0.
  warnings.warn(
/Users/michaelshwe/opt/anaconda3/lib/python3.9/site-packages/airflow/configuration.py:443: FutureWarning: The 'log_id_template' setting in [elasticsearch] has the old default value of '{dag_id}-{task_id}-{execution_date}-{try_number}'. This value has been changed to '{dag_id}-{task_id}-{run_id}-{map_index}-{try_number}' in the running config, but please update your config before Apache Airflow 3.0.
  warnings.warn(
/Users/michaelshwe/opt/anaconda3/lib/python3.9/site-packages/airflow/configuration.py:549 DeprecationWarning: The sql_alchemy_pool_enabled option in [core] has been moved to the sql_alchemy_pool_enabled option in [database] - the old setting has been used, but please update your config.
/Users/michaelshwe/opt/anaconda3/lib/python3.9/site-packages/airflow/configuration.py:549 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
/Users/michaelshwe/opt/anaconda3/lib/python3.9/site-packages/airflow/configuration.py:549 DeprecationWarning: The sql_alchemy_schema option in [core] has been moved to the sql_alchemy_schema option in [database] - the old setting has been used, but please update your config.
/Users/michaelshwe/opt/anaconda3/lib/python3.9/site-packages/airflow/configuration.py:549 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
/Users/michaelshwe/opt/anaconda3/lib/python3.9/site-packages/airflow/configuration.py:549 DeprecationWarning: The max_db_retries option in [core] has been moved to the max_db_retries option in [database] - the old setting has been used, but please update your config.
[2022-10-19 11:22:44,096] {utils.py:147} INFO - Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2022-10-19 11:22:44,096] {utils.py:159} INFO - NumExpr defaulting to 8 threads.
Astro SQL CLI 0.0.9
```

**Version**
* SQL CLI: 0.0.9
* OS: MacOS

**To Reproduce**

1. Install Anaconda3
2. Install astro-sql-cli
3. Try to run any flow command

**Expected behaviour**

Commands should not be printing warnings. Example of how the version command should look like:
```
$  flow version
Astro SQL CLI 0.0.9
```

**Comment by dimberman** [comment]
@mikeshwe I'm unable to reproduce this. Do you want to jump on a call tomorrow to see what's going on?

```
(sql-cli) astro-sdk $(parse_git_branch)  $(ps1_kube) $
flow version
Astro SQL CLI 0.0.9
(sql-cli) astro-sdk $(parse_git_branch)  $(ps1_kube) $
flow version
Astro SQL CLI 0.0.9
(sql-cli) astro-sdk $(parse_git_branch)  $(ps1_kube) $
```

**Comment by feluelle** [comment]
I am also unable to reproduce this with 0.0.9.

**Comment by kaxil** [comment]
What version of Airflow is installed on Mike's machine?

**Comment by mikeshwe** [comment]
Daniel and I tried a number of fixes, still have the same problem.

```
conda deactivate
python -m venv sql-env
pip install astro-sql-cli
```

**Comment by tatiana** [comment]
@mikeshwe could you tell us the output of running the following commands, please:
```
conda --version
python --version
```
Also, could you confirm if you have any virtual environments set related to Airflow ATM:
```
env | grep AIRFLOW*
```

**Comment by kaxil** [comment]
also the output of the following would be helpful:

```
airflow version
```

**Comment by feluelle** [comment]
My guess is that your airflow home is set to an older airflow environment than what you installed with the astro-sql-cli. The warnings come from the airflow.cfg.

Could you try setting "--airflow-home" as an option in the init command? Choose any folder other than the old one (which is probably "~/airflow").

**Comment by mikeshwe** [comment]
> @mikeshwe could you tell us the output of running the following commands, please:
> 
> ```
> conda --version
> python --version
> ```
> 
> Also, could you confirm if you have any virtual environments set related to Airflow ATM:
> 
> ```
> env | grep AIRFLOW*
> ```
conda 22.9.0
Python 3.10.8

(sql-env) michaelshwe@Michaels-MBP-4 ~ % env | grep AIRFLOW*
zsh: no matches found: AIRFLOW*

**Comment by mikeshwe** [comment]
> 

(sql-env) michaelshwe@Michaels-MBP-4 ~ % airflow version
/opt/homebrew/lib/python3.9/site-packages/airflow/configuration.py:276: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(sqlite3.sqlite_version) < StrictVersion(min_sqlite_version):
2.2.5

**Comment by feluelle** [comment]
Thank you @mikeshwe for all the information and the error output - this is really helpful.

So it seems you are running airflow `2.2.5` which is fine. We have not tested it with that version yet, but in our version requirement we allow airflow version `>2.0`. We only have automated tests for the latest airflow version right now.

The error you are facing is due to the config option [sql_alchemy_conn](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#sql-alchemy-conn-deprecated) which has been moved from `core` to `database` - and we have written the code only to work for `database` which is only the case for Airflow `>2.3`. Since you are on `2.2.5` your config has the option in `core`.

@tatiana we should start to either add automatic testing for all supported airflow versions i.e. `>2.0` or set the airflow version to `>2.4`. So that users install the (current) latest airflow version which we already test in CI. My suggestion is to change it to `>2.3` at least and with that we also add tests for 2.3 in CI. I am afraid we have to change a lot of code to make it compatible to `>2.0`. @mikeshwe would that work for you?

**Comment by mikeshwe** [comment]
Thanks @feluelle ! I usually run Airflow on my machine using Astro and Docker, so my native Airflow installation is prone to get outdated. Please see attached for Airflow error when I try to upgra
[error.txt](https://github.com/astronomer/astro-sdk/files/9862622/error.txt)
de.

**Comment by mikeshwe** [comment]
Working now. I was able to debug with @tatiana . I think the things that fixed were:

- `export PYTHONWARNINGS="ignore"  `
- `which airflow` and `which flow` showed us that homebrew installs were the defaults, so we renamed those.
