### ISSUE TITLE
Remove SQL CLI help duplication

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#1137]
**Context**

As of SQL CLI 0.1, we are duplicating the definition of `help` originally declared using the Python `typer` library and Go Cobra (a tool used by the Astro CLI to implement CLI).

As of 25 October, we investigated a few alternatives - but given the deadline time and the fact we need to parse the command line to mount Docker volumes, we opted to duplicate them - for the 0.1 delivery.

**Goal**

* Help commands are declared only within the Python SQL CLI
* There are no SQL CLI help declarations within the Astro CLI

**Comment by feluelle** [comment]
During investigation of removing cobra sub-commands for flow e.g. `init`, `validate`, etc., I came across this [issue](https://github.com/spf13/cobra/issues/739) which explains the complexity we would have to deal with when trying to remove the cobra sub-commands.

**Comment by pankajkoti** [comment]
We are able to achieve this now with the commit: https://github.com/astronomer/astro-cli/pull/819/commits/00a94d374498d0ddea35e31e202d32c60268517b

**Comment by tatiana** [comment]
Excellent, @pankajkoti, thanks a lot - closing this ticket
