### ISSUE TITLE
[SPIKE/RESEARCH]:Add Duck DB support

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#1138]

**Comment by kaxil** [comment]
@jlaneve has built a provider for DuckDB on https://github.com/astronomer/airflow-provider-duckdb which is released on https://pypi.org/project/airflow-provider-duckdb/

**Comment by pankajastro** [comment]
> @jlaneve has built a provider for DuckDB on https://github.com/astronomer/airflow-provider-duckdb which is released on https://pypi.org/project/airflow-provider-duckdb/

Thank you @kaxil for sharing it. I have also started exploring it, I have a branch in our airflow repo for now but a bit of testing https://github.com/astronomer/airflow/tree/duckdb_provider

**Comment by sunank200** [comment]
Duckdb doesn't seem to be part of external dialects of Sqlachemy: https://docs.sqlalchemy.org/en/20/dialects/ Also there is one library( https://pypi.org/project/duckdb-engine/ ) which acts as SQLAlchemy driver for [DuckDB](https://duckdb.org/) but this is not maintained well. In this case, all the methods for the base databases have to be overridden as is no SQLAlchemy support. This would increase the time for implementation and the tests.

cc: @utkarsharma2 @phanikumv

**Comment by sunank200** [comment]
There is an issue already on duckdb: https://github.com/duckdb/duckdb/issues/305

**Comment by sunank200** [comment]
This is a [PR](https://github.com/Mause/duckdb_engine/pull/439) on duckdb-engine for SQLAlchemy support for 2.0 But its very old

**Comment by sunank200** [comment]
Used [duckdb-engine](https://github.com/Mause/duckdb_engine) for SQLALchemy driver as per discussion in https://astronomer.slack.com/archives/C03868KGF2Q/p1675274903489399
