### ISSUE TITLE
Specifying table of different DB in Output_table param fails silently

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#1147]
**Describe the bug**
Refer to slack thread - https://astronomer.slack.com/archives/C02B8SPT93K/p1664979020078039

**Version**
* Astro: 1.2.0

**Expected behavior**
We should raise an exception in case the table is from a different DB.

**Comment by phanikumv** [comment]
Seems to be risky for 1.2.1 release considering other priorities

**Comment by pankajastro** [comment]
just wondering why didn't throw an error in this case.

**Comment by pankajastro** [comment]
@utkarsharma2 what we should check here source and target table conn_type or db_name also?
```
if source_table.conn_type != target_table.conn_type:
   raise
```
