### ISSUE TITLE
Enhance coverage for SQL CLI integration in Astro CLI

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astro-sdk#1153]
We've merged the integration PR in Astro CLI with a caveat that we lowered the coverage lower bound to 85% for the PR to be merged, so that an alpha release could be made available for testing out the integration.
It is expected that we increase the coverage now before the release is out and made available publicly.

**Comment by tatiana** [comment]
Merged:
https://github.com/astronomer/astro-cli/pull/849
