### ISSUE TITLE
Enhance `AppendOperator` to not use Temp tables

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#1158]
**Please describe the feature you'd like to see**
Append Dataframe contents to a SQL table without an intermediate tmp table.At the moment a workaround is to set output_table to a TempTable object.
Refer to https://apache-airflow.slack.com/archives/C048DK0ML8J/p1666989876122549

**Describe the solution you'd like**
A clear and concise description of what you want to happen, if possible with code examples.

**Are there any alternatives to this feature?**
Is there another way we could solve this problem or enable this use-case?

**Additional context**
Add any other context about the feature request here.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by pankajastro** [comment]
Where does the intermediate tmp table we create in load_file? Does the user trying to load a dataframe in the SQL table here?

**Comment by pankajastro** [comment]
spoke to the user the use case here is to append a dataframe in a SQL table

**Comment by pankajastro** [comment]
We recently made a change to allow dataframe operator to append a dataframe in SQL table https://github.com/astronomer/astro-sdk/issues/1379 so maybe dataframe operator will be right choice of this usecase

**Comment by tatiana** [comment]
@pankajastro, as we discussed, I feel that having this feature in `append` is much more intuitive than using the `aql.dataframe` as in #1379. If we had to choose between both implementations, my vote would be for `append`.

**Comment by pankajastro** [comment]
> @pankajastro, as we discussed, I feel that having this feature in `append` is much more intuitive than using the `aql.dataframe` as in #1379. If we had to choose between both implementations, my vote would be for `append`.

@sunank200 @phanikumv WDYT on this?

**Comment by sunank200** [comment]
@pankajastro I feel if the user just wants to append a data frame in a SQL table, then `append`  is the better choice. But if the user uses this for intermediate results then ` aql.dataframe` as in https://github.com/astronomer/astro-sdk/issues/1379n would make sense.

**Comment by pankajastro** [comment]
currently, you can use dataframe operator for this use case. please re-open it if you need more help. thank you.
