### ISSUE TITLE
Generated DAGS are going into .airflow/dags instead of dags directory

### ISSUE THREAD

**Issue by mikeshwe** [astronomer/astro-sdk#1230]
**Describe the bug**

**Version**
* Astro CLI 1.7
* SQL CLI 0.1.1
* OS: [eg. Debian]

**To Reproduce**
`astro flow init --airflow-dags-folder=dags `
`astro flow run example_basic_transform
`astro flow run example_templating --env=dev`

the dag for `example_basic_transform` shows up in the correct spot, but not for `example_templating`

Guessing it's because of `--env=dev`

**Expected behavior**

**Screenshots**
![Screen Shot 2022-11-09 at 12 09 32 PM](https://user-images.githubusercontent.com/4237498/200930987-0d5bafaa-deaf-4ad4-8cf2-a85481293f77.png)

**Additional context**

**Comment by vikramkoka** [comment]
Ah, that's really weird. 
cc: @utkarsharma2

**Comment by tatiana** [comment]
One resolution for this problem would be to have a global configuration to store the configuration which is not environment specific. But there may be other solutions @feluelle @pankajastro @dimberman @kaxil

**Comment by kaxil** [comment]
You can probably add a `AIRFLOW__CORE__DAGS_FOLDER` in https://github.com/astronomer/astro-sdk/blob/main/sql-cli/sql_cli/__init__.py so any command run from SQL CLI will have that set.

**Comment by tatiana** [comment]
We'll be releasing the SQL CLI python package with this fix, but - from an Astro CLI perspective - we'll also need to have this merged: https://github.com/astronomer/astro-cli/pull/924. We'll be negotiating to have a 1.8 patch release with this fix, but in the worse case, it should be part of the Astro CLI 1.9.

**Comment by tatiana** [comment]
Since we completed the Python part relevant to the 0.2.2 release, I'll consider this ticket closed. We should have a patch release of Astro CLI 1.8 containing the mentioned change (probably 1.8.4).
