### ISSUE TITLE
Test the XCOM Pickling changes as part of Airflow 2.5.0 Rc

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astro-sdk#1232]
**Please describe the feature you'd like to see**
A clear and concise description of what problem feature solves or what use-case it would enable.
e.g. "I really wish I could ...", "I'm sad that I can't..."

**Describe the solution you'd like**
A clear and concise description of what you want to happen, if possible with code examples.

**Are there any alternatives to this feature?**
Is there another way we could solve this problem or enable this use-case?

**Additional context**
Add any other context about the feature request here.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by phanikumv** [comment]
Disabled pickling, used latest code on main branch along with astro-runtime 7.0.0 alpha2 and used the below env. variables

```
AIRFLOW__ASTRO_SDK__XCOM_STORAGE_CONN_ID: aws_s3_default
AIRFLOW__ASTRO_SDK__XCOM_STORAGE_URL: s3://xcombucket/xcomfolder/
```

Tried to save dataframe as xcom in s3.

```
load_table_with_data = aql.load_file(
   input_file=File(path=f"{S3_BUCKET_NAME_SOURCE}/crxbank1.csv",
                   filetype=FileType.CSV, conn_id=AWS_CONN_ID),
   task_id="load_csv_data_bank1",
   outlets=[Dataset("snowflake://crx_data_bank1")],
   do_xcom_push=True
)
```

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/94376113/204352659-bb4fe9bf-b79e-453f-8a0b-6c175c725086.png">

```
load_table_with_data = aql.load_file(
   input_file=File(path=f"{S3_BUCKET_NAME_SOURCE}/crxbank1.csv",
                   filetype=FileType.CSV, conn_id=AWS_CONN_ID),
   task_id="load_csv_data_bank1",
   output_table=crx_data_table,
   outlets=[Dataset("snowflake://crx_data_bank1")],
   do_xcom_push=True
)
```

<img width="1526" alt="image" src="https://user-images.githubusercontent.com/94376113/204353124-0a7a2fcf-9c0a-48ff-bc66-3a5b63c45c6a.png">
