### ISSUE TITLE
dataframe operator is now appending to it's output table instead of replacing.

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#1260]
**Describe the bug**
 the dataframe operator is now appending to it's output table instead of replacing.
refer to https://astronomer.slack.com/archives/C02B8SPT93K/p1668643987896139

**Version**
* Astro: [e.g. 0.6.0]
* OS: [eg. Debian]

**To Reproduce**
1. Write the DAG  '...'
2. Create connection '....'
3. Run using  '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kaxil** [comment]
This was caused after the upgrade from 1.1.1 (working) to 1.2.1 (causing dupes)

**Comment by sunank200** [comment]
Related to this as well: https://github.com/astronomer/astro-sdk/issues/1273
