### ISSUE TITLE
Add a delimiter to load_file() operator for CSV files

### ISSUE THREAD

**Issue by magdagultekin** [astronomer/astro-sdk#1264]
**Please describe the feature you'd like to see**
related-to: #482 
Currently, we cannot pass a delimited when loading a CSV file. 

**Describe the solution you'd like**
I'd like to be able to say that for example `$` is a delimiter, not `,`. When made available, it should also be reflected in the documentation. 
1. Spike task to see how all native libraries take care of delimiter.
2. Change the current flow accordingly.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by pankajastro** [comment]
@magdagultekin we have `native_support_kwargs` param if you want to pass the native API param in case of the load file here we have one tests https://github.com/astronomer/astro-sdk/blob/main/python-sdk/tests_integration/sql/operators/test_load_file.py#L445

**Comment by tatiana** [comment]
At the moment, the `native_support_kwargs` solution described by @pankajastro currently probably works like this (untested):

* GCS -> BigQuery
```
native_support_kwargs={"fieldDelimeter": "$"}
```
* S3 -> Redshift
```
native_support_kwargs={"DELIMITER": "$"}
```

We still need to implement solutions for the following:
* non-native (e.g. S3 -> Postgres)
* S3 -> BigQuery
* GCS -> Snowflake

**Comment by tatiana** [comment]
@pankajastro suggested adding examples for these, I think that would be very valuable!

**Comment by pankajastro** [comment]
Moving this to 1.5.0 for the native path parameter improvement

**Comment by phanikumv** [comment]
Let's create a new ticket for [supporting generic load options for big query and redshift](https://github.com/astronomer/astro-sdk/issues/1599). Closing this.
