### ISSUE TITLE
Check if we can remove 'pragma: no cover' tag for missing code coverage on imports

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astro-sdk#1283]
In our code base, for a few imports which are added when TYPE_CHECKING is set to true, we're adding the tag
'pragma: no cover' as those lines are not covered by tests. Investigate if we can cover those lines.

**Comment by feluelle** [comment]
I really don't think we can as per https://github.com/astronomer/astro-sdk/pull/1258#discussion_r1029169535

**Comment by feluelle** [comment]
cc @tatiana
