### ISSUE TITLE
Make the URLs in S3 for example DAG public 

### ISSUE THREAD

**Issue by sunank200** [astronomer/astro-sdk#1299]
**Describe the bug**
The data is not available to users who want to try out this DAG for the first time in example DAG as the S3 bucket is not public. We can make the folder `python_sdk/example_dags/data` public in `s3://astro-sdk`

**Comment by rajaths010494** [comment]
@sunank200 is this issue done?

**Comment by sunank200** [comment]
This can be closed as we have data on the S3 bucket in the example DAG. Instead of making it public, we can have data locally.
