### ISSUE TITLE
Example S3 connection for SQL-CLI

### ISSUE THREAD

**Issue by mikeshwe** [astronomer/astro-sdk#1326]
**Please describe the feature you'd like to see**

~/config/dev/configuration.yml should contain a template for what an S3 connection looks like

**Comment by pankajkoti** [comment]
@mikeshwe What would the example be wrt to S3. Do we mean load file from S3 to Redshift ?

**Comment by mikeshwe** [comment]
s3 to redshift or s3 to snowflake. Mostly just need to know how to set up
the config for S3, and ideally we'd have something in our tests that goes
e2e from s3 to RS or SF.

**Comment by feluelle** [comment]
Fixed by #1398
