### ISSUE TITLE
Fix CI failures found while testing SDK with airflow 2.5.0

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#1337]
**Describe the bug**
Failing jobs on CI:

- [ ] https://github.com/astronomer/astro-sdk/actions/runs/3588515052/jobs/6039998660
- [ ] https://github.com/astronomer/astro-sdk/actions/runs/3588515052/jobs/6039999158
- [ ] https://github.com/astronomer/astro-sdk/actions/runs/3588515052/jobs/6039999242
- [ ] https://github.com/astronomer/astro-sdk/actions/runs/3588515052/jobs/6039999316
- [ ] https://github.com/astronomer/astro-sdk/actions/runs/3588515052/jobs/6039999397
- [ ] https://github.com/astronomer/astro-sdk/actions/runs/3588515052/jobs/6039999475
- [ ] https://github.com/astronomer/astro-sdk/actions/runs/3588515052/jobs/6039999567

Related to  https://github.com/astronomer/astro-sdk/pull/1334 and https://github.com/astronomer/astro-sdk/pull/1331 and https://github.com/astronomer/astro-sdk/pull/1319

**Comment by feluelle** [comment]
Fixed by #1317
