### ISSUE TITLE
Test Python Astro-SDK with Airflow RC / Providers RC

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#1356]
Test SDK as soon as a new release of Airflow RC or Providers RC is available.

**Comment by phanikumv** [comment]
@rajaths010494 will test astro-sdk on airflow 2.5.1 through CI  and post the results

**Comment by rajaths010494** [comment]
https://github.com/astronomer/astro-sdk/actions/runs/3930890612/jobs/6721454566
https://github.com/astronomer/astro-sdk/pull/1600

**Comment by rajaths010494** [comment]
https://github.com/astronomer/astro-sdk/pull/1600

**Comment by rajaths010494** [comment]
https://github.com/astronomer/astro-sdk/pull/1600
