### ISSUE TITLE
Modify example dag test case to make sure all the dags are running 

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#1358]
**Please describe the feature you'd like to see**
Make sure all the example dags are running on CI

**Comment by rajaths010494** [comment]
<img width="2552" alt="Screenshot 2022-12-09 at 5 08 27 PM" src="https://user-images.githubusercontent.com/92459020/206694779-f16829d3-9d9d-4731-beb4-855792b32169.png">
Ran the test case for example dags all 18 dag ids were ran and attaching screenshot of it.  All dags have been triggered.
