### ISSUE TITLE
Clean up operator failing

### ISSUE THREAD

**Issue by sunank200** [astronomer/astro-sdk#1359]
**Describe the bug**
When I'm running [this](https://github.com/astronomer/qa-scenario-dags/blob/master/astro_sdk/example_dynamic_task_template.py) dag getting below error -
string"  File "/usr/local/lib/python3.9/site-packages/astro/sql/operators/cleanup.py", line 235, in resolve_tables_from_tasks"
38:string"    for t in task.output.resolve(context):"
39:string"AttributeError: 'MappedOperator' object has no attribute 'output'"
Is this expected ?

Raised by @jyotsa09

**Comment by feluelle** [comment]
The `output` was implemented in 2.4.0 according to the release notes (see [here](https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#id13))
> Add output property to MappedOperator [(#25604)](https://github.com/apache/airflow/pull/25604)

A possible fix would be to use `XComArg(...)` instead.
