### ISSUE TITLE
Subscribe to Astro CLI E2E tests failure

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astro-sdk#1394]
We have setup e2e tests as part of https://github.com/astronomer/astro-sdk/issues/1234.

Now we want to get notified whether the CI runs passing or failing, preferable via slack into a channel.

**Comment by feluelle** [comment]
I have added everyone from the sql-cli team to the slack group which gets notified in astro-e2e-alerts channel if the circle ci pipeline fails.

**Comment by feluelle** [comment]
WDYT @tatiana @dimberman @pankajkoti ? Do you think this is sufficient?

**Comment by pankajkoti** [comment]
I guess, yes, is sufficient
