### ISSUE TITLE
Fix deepsource issues

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#1422]
**Describe the bug**

<img width="890" alt="image" src="https://user-images.githubusercontent.com/94376113/207391000-01ed8b10-1504-480d-8cfc-e26672af4e55.png">

**Version**
* Astro: [e.g. 0.6.0]
* OS: [eg. Debian]

**To Reproduce**
1. Write the DAG  '...'
2. Create connection '....'
3. Run using  '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by phanikumv** [comment]
Above issues are resolved, we'll log another ticket in case new issues arise

**Comment by sunank200** [comment]
@phanikumv is there a PR for this issue?
