### ISSUE TITLE
Improve the Azure location implementation

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#1446]
**Context**

There are a few points which could be improved from the PR #1275.

They are:
* Use the `wasb_default_conn` for WASB tests (both in the `conftest.py` and in `integration_tests/files/locations/test_wasb.py`. Stop using `AIRFLOW_CONN_WASB_DEFAULT`
* Improve the complexity of the fixture `remote_files_fixture`  and of the method `_upload_or_delete_remote_file`, available in the `integration_tests/conftest.py`
* Replace the usage of the `_get_blob_client` by a non "internal use method

**Comment by utkarsharma2** [comment]
Closing this since all three PRs are merged.
