### ISSUE TITLE
Allow load and export from Azure Blob storage (WASB) using native path

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#1448]
**Please describe the feature you'd like to see**
Once we've introduced the Azure Blob Storage file location (WASB) #905 #1275 the next step is to make sure we can have load and export operations using the native path.

Relates to: #1447

**Describe the solution you'd like**
Users should be able to load and export files using WASB using the native path

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of the methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by phanikumv** [comment]
No native path is available for export from Azure as discussed in the sprint planning.

**Comment by utkarsharma2** [comment]
As per my discussion with @tatiana we only native path for load_file and not export_file.
for load_file() there are two paths:
1. Snowflake-Azure - PR: https://github.com/astronomer/astro-sdk/pull/1675
2. Bigquery-Azure - Internal issue with Bigquey, which only bigquery can handle, we have raised a ticket with google for this. Ticket - https://github.com/astronomer/astro-sdk/issues/1485
