### ISSUE TITLE
Create compatibility matrix for astro-cli to sql-cli versions

### ISSUE THREAD

**Issue by feluelle** [astronomer/astro-sdk#1582]
From a recent slack discussion I (Felix) had with Neel, we noticed that the current way we handle sql-cli upgrades in the astro-cli is very contra-productive and probably slows down both teams more than it helps.

This is because changes released in the sql-cli immediately need to be aligned with the astro-cli version as it currently always installs the latest version of the sql-cli.

To prevent that from happening, we create a compatibility matrix which maps versions or sets up constraints so that automatically the newest supported sql-cli version will be used in the astro-cli.

```
{
    "astroCLICompatibility": {
        "1.8": {
            "astroSDKPythonVersion": ">=1.3.0, <1.5"
        }
}
```

Configuration file, branch `astro-cli`:
https://github.com/astronomer/astro-sdk/blob/astro-cli/sql-cli/config/astro-cli.json

**Comment by tatiana** [comment]
This problem is similar to: #1473
