### ISSUE TITLE
Add interface to get results in standard formats from run_raw_sql

### ISSUE THREAD

**Issue by jlaneve** [astronomer/astro-sdk#1583]
**Please describe the feature you'd like to see**

When I use `aql.run_raw_sql`, I find myself writing handlers like:

```python
@aql.run_raw_sql(..., handler = lambda x: x.fetchall())
```

```python
@aql.run_raw_sql(..., handler = pd.DataFrame(x.fetchall(), columns = x.keys()))
```

It seems like there are a few natural results formats (list, dataframe) that you'd want to get results in, but the user is responsible for making these handlers. Additionally, I can't just use the same handler for both `SELECT` and `CREATE TABLE` functions because sqlalchemy's ResultProxy errors if there are no results and you call `x.fetchall()`

**Describe the solution you'd like**
Add two fields to the decorator/operator:
- `results_format`: let the user specify a common format they want their results (list, dataframe)
- `fail_on_empty`: let the user decide what the behavior should be if there are no results

**Are there any alternatives to this feature?**

We could also consider exporting common handlers instead of forcing the user to define them.

**Additional context**
Add any other context about the feature request here.

I'm considering this from the perspective of the Astro Cloud IDE, in which our requirements are:
- get the results as a DataFrame
- use the same decorator/code for all run_raw_sql's, regardless of wether it's a `SELECT` or `INSERT`
  - this is because we're generating a DAG and parsing the SQL code to do this dynamically is unreliable

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by utkarsharma2** [comment]
We need to update/add documentation for these new params. Will take care in a separate PR.
