### ISSUE TITLE
Add Pandas Serializer in SDK for Airflow 2.6

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#1590]
https://github.com/apache/airflow/pull/28067 adds support for creating custom serialization modules which we should use to add a serializer for Pandas in either Astro SDK or Apache Airflow itself. 

We should align the timelines with Airflow 2.6 release as this feature depends on Airflow 2.6. This will be a different way for serializing dataframes similar to how we achieved the same for Airflow 2.5 using the code in https://github.com/astronomer/astro-sdk/blob/a59097ce77546dd66ca724ed38c95da032950f88/python-sdk/src/astro/dataframes/pandas.py

Acceptance Criteria:
- [ ] It should not break installations with Airflow < 2.6
- [ ] Pandas Dataframe should be serialized to json

**Comment by sunank200** [comment]
When are we planning to release 2.6 @ashb ?

**Comment by kaxil** [comment]
That is a question for Jed or Ephraim. Could you sync up with either of them

**Comment by utkarsharma2** [comment]
There is no date for milestones added yet. - https://github.com/apache/airflow/milestone/67

**Comment by sunank200** [comment]
@utkarsharma2 to sync with @jedcunningham and plan this ticket.

**Comment by sunank200** [comment]
@utkarsharma2 spoke with @jedcunningham. They are targeting March end for this. So deferring it to 1.6.0 or later releases.

**Comment by sunank200** [comment]
@utkarsharma2 are we still targeting March end for this? If not how does the timeline look for this?

**Comment by sunank200** [comment]
@utkarsharma2 are we still targeting March end for this? If not how does the timeline look for this?
