### ISSUE TITLE
Check Python SDK version to be promoted is not already part of requirements.txt

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astro-sdk#1640]
Currently, we only check that that the runtime image is incompatible meaning that it does not have the required PythonSDK version installed in it before prompting the user to add the required version to requirements.txt.
We should also check that the same version has not already been added to the requirements.txt before prompting the user for confirmation.

**Comment by tatiana** [comment]
@pankajkoti should we add this as bug, since this behaviour was specified in the original ticket?
https://github.com/astronomer/astro-sdk/issues/1473

**Comment by pankajkoti** [comment]
yes @tatiana . I added the `bug` label now. Do we need to do something more to mark it so?
