### ISSUE TITLE
Get astro flow version and pass it to deploy flow to match the key in compatibility matrix

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astro-sdk#1642]
Since we don't pin SQL CLI versions to be installed and have it as a pip like constraint specification, 
we need to get the installed version of SQL CLI and use it in the compatibility matrix to find the
corresponding Python SDK constraints.

**Comment by tatiana** [comment]
This was released yesterday as part of a new Astro CLI 1.10 pre-release
