### ISSUE TITLE
Clean up tables on snowflake for temporary table

### ISSUE THREAD

**Issue by sunank200** [astronomer/astro-sdk#1663]
**Describe the bug**
Seems like the clean-up is not working properly for snowflake as aspected. There are many tables which are there in https://app.snowflake.com/us-east-1/gp21411/#/data/databases/SANDBOX/schemas/ASTROFLOW_CI/table

@rajaths010494 WDYT?

**Comment by sunank200** [comment]
@rajaths010494 could you update your findings and approach you had discussed last week on this ticket please

**Comment by rajaths010494** [comment]
Cleaned up temp tables in snowflake. 
To add some identifiers for temp tables for test cases and see which is causing it.
But when a PR is raised and tests are running, if the user makes a commit again, then the tests are stopped, in which case the temp tables aren't deleted.

**Comment by sunank200** [comment]
@rajaths010494 lets add an issue to clean up the snowflake tables for failed runners as discussed.

**Comment by sunank200** [comment]
Also, could you post the screenshot of cleaned-up tables from snowflake UI, please?

**Comment by rajaths010494** [comment]
> clean up the snowflake tables for failed runners

https://github.com/astronomer/astro-sdk/issues/1682.

**Comment by rajaths010494** [comment]
When tmp tables exist
<img width="1557" alt="Screenshot 2023-01-30 at 6 37 54 PM" src="https://user-images.githubusercontent.com/92459020/215488693-54b7fb70-2a74-452e-a1f5-e188a5e53a58.png">

After deletion
<img width="1057" alt="Screenshot 2023-01-30 at 6 47 05 PM" src="https://user-images.githubusercontent.com/92459020/215488766-86b23c3c-ccc3-4a1c-bdd5-52349c893c64.png">

**Comment by sunank200** [comment]
@rajaths010494 as discussed we concluded to use implementation similar to astronomer-providers for the clean-up

**Comment by rajaths010494** [comment]
Have added an dag to clean up resources as part of astro cloud running all of our example dags

**Comment by rajaths010494** [comment]
Have added an dag to clean up resources as part of astro cloud running all of our example dags

**Comment by sunank200** [comment]
https://github.com/astronomer/astro-sdk/issues/913

**Comment by sunank200** [comment]
This PR: https://github.com/astronomer/astro-sdk/pull/1499 adds the clean DAG as part of CI. Follow up ticket added to create named tables as part of tests
