### ISSUE TITLE
Update SQL CLI compatibility implementation so support matching without the micro digit

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#1673]
**Please describe the feature you'd like to see**
At the moment, as discussed in https://github.com/astronomer/astro-sdk/pull/1671#discussion_r1085368779, our compatibility keys are represented by `<major>.<minor>.<micro>` as:
```
{
  "astroCliCompatibility": {
    "1.10.0": {
      "preRelease": true,
      "sqlCliVersion": ">0.2.2"
    },
    "1.8.0": {
      "preRelease": false,
      "sqlCliVersion": ">0.2, <0.3"
    },
    "1.9.0": {
      "preRelease": false,
      "sqlCliVersion": ">0.2, <0.3"
    }
  },
  "baseDockerImage": "quay.io/astronomer/astro-runtime:6.0.4-base",
  "compatibility": {
    "0.3.1": {
      "astroRuntimeVersion": ">=7.2.0",
      "astroSDKPythonVersion": ">=1.3.1"
    },
    ">0.2.2": {
      "astroRuntimeVersion": ">=7.2.0",
      "astroSDKPythonVersion": ">=1.3.1"
    }
  }
}
```
Ideally, we'd also be able to use just `<major>.<minor>` versions as keys, so we don't need to update the file for every Astro CLI/SQL CLI release, unless necessary:
```
{
  "astroCliCompatibility": {
    "1.10.2": {
      "preRelease": true,
      "sqlCliVersion": "<0.3.2"
    },
    "1.10": {
      "preRelease": true,
      "sqlCliVersion": ">0.2.2"
    },
    "1.8": {
      "preRelease": false,
      "sqlCliVersion": ">0.2, <0.3"
    },
    "1": {
      "preRelease": false,
      "sqlCliVersion": ">0.2, <0.3"
    }
  },
  "baseDockerImage": "quay.io/astronomer/astro-runtime:6.0.4-base",
  "compatibility": {
    "0.3": {
      "astroRuntimeVersion": ">=7.2.0",
      "astroSDKPythonVersion": ">=1.3.1"
    },
  }
}
```
Also, we need to make sure that if there is a new (minor) Astro CLI release, we don't fail - we should fallback to the sqlCliVersion non-prelease version in those cases.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by pankajkoti** [comment]
The plan is to take the following steps for version matching:
1. Try to find an exact match in the compatbility matrix e.g. 1.10.0
2. If not exact match found, trim the version to remove the patch version and match until the minor version e.g. 1.10
3. If still does not match, match a key named 'default' which is set to installed latest SQL CLI version.
