### ISSUE TITLE
Check run_sql method returns result rather than CursorResult

### ISSUE THREAD

**Issue by rajaths010494** [astronomer/astro-sdk#1710]
Currently,  run_sql method returns CursorResult instead of which we can return the result.
we do have data bricks where we use a handler to get the results and explore even in other databases we could do the same and return the result rather than CursorResult.

@dimberman

**Comment by sunank200** [comment]
@rajaths010494 what does the priority for this task look like?

**Comment by rajaths010494** [comment]
We can close this as this done part of https://github.com/astronomer/astro-sdk/pull/1773
