### ISSUE TITLE
Create a named temp tables on test with identifier for each test for cleanup

### ISSUE THREAD

**Issue by sunank200** [astronomer/astro-sdk#1712]
**Describe the bug**
Create a named temp table on the test with the identifier for each test for cleanup. More context onhttps://github.com/astronomer/astro-sdk/issues/1663

**Comment by sunank200** [comment]
@rajaths010494 to start to day for the clean up.

**Comment by rajaths010494** [comment]
Created the PR for leaky test cases but was unable to run on CI due to https://github.com/astronomer/astro-sdk/actions/runs/4162357575/jobs/7201435983

**Comment by sunank200** [comment]
Blocked on https://github.com/astronomer/astro-sdk/pull/1757

**Comment by sunank200** [comment]
@rajaths010494 can rebase from the https://github.com/astronomer/astro-sdk/pull/1757 branch and unblock for now till CI is resolved on main branch.

**Comment by rajaths010494** [comment]
Today will rebase this and try to check non deleted temp tables
