### ISSUE TITLE
Implement a transfer workflow for BigQuery [non-native]

### ISSUE THREAD

**Issue by sunank200** [astronomer/astro-sdk#1732]
**Please describe the feature you'd like to see**
- Add `DataProvider` for Bigquery - read/write methods
- Add non-native transfer implementation for GCS to BigQuery
-  Add non-native transfer implementation for S3 to BigQuery
- Add non-native transfer example DAG for BigQuery to Sqlite 
- Add non-native transfer example DAG for BigQuery to Snowflake
- Add example DAG
- Add tests with 90% coverage

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by utkarsharma2** [comment]
@rajaths010494  is done with the write operation is done, working on the read operation.

**Comment by rajaths010494** [comment]
On read operations, was able to  convert table to pandas dataframe but for writing into databases currently needs an actual file to be present. So created an local temp file with local connections.

**Comment by rajaths010494** [comment]
Added read operations from bigquery to snowflake using a local file.
