### ISSUE TITLE
Implement a transfer workflow for GCS to Snowflake [non-native]

### ISSUE THREAD

**Issue by sunank200** [astronomer/astro-sdk#1735]
**Please describe the feature you'd like to see**
- Add `Dataprovider` for Databases
- Add `DataProvider` for Snowflake
- Add non-native transfer implementation for GCS to Snowflake
- Add example DAG
- Tests

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by rajaths010494** [comment]
Connected with @dimberman  and added ticket https://app.zenhub.com/workspaces/dag-authoring-team-astro-sdk-61e7a085a496df00172965bd/issues/gh/astronomer/astro-sdk/1789 have created the ticket for further discussions.
