### ISSUE TITLE
[Improvement] Running example dag on astro cloud using Sqlite on multiple workers

### ISSUE THREAD

**Issue by rajaths010494** [astronomer/astro-sdk#1737]
**Please describe the feature you'd like to see**
Currently, we are using SQLite-based dag for transform, merge and append when running on astro cloud since there can be more than 1 worker.  When a different worker is assigned to transform, merge or append then the dag will fail with the table not found. and now we are setting the worker slots to 1 so all tasks run on the same worker.
SQLite is not a network-based database so it doesn't have any network connection ability built into it.
1.  Make SQLite access as mount volume to workers.
2. Find an existing library which does the point 1

**Describe the solution you'd like**
To increase the worker slot in astro cloud we need to change the SQLite connection of these dags to other database connections.
Preferably Postgres.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Run the dags on astro cloud for multiple workers
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)

- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by sunank200** [comment]
This ticket would maximum of half a day.

**Comment by sunank200** [comment]
@rajaths010494 has fixed the issue sqlite. He needs to fix it for DuckDB as well. for DuckDB he is figuring out a way to use the DuckDB file from S3. More details on https://duckdb.org/docs/extensions/overview.html

**Comment by rajaths010494** [comment]
Tried to get httpfs for s3 we need to mount and other approaches has applications running where dDuckDb is running for connection, not from the network.

Will try to talk to the internal astronomer team and see if we can get a container up in the same cluster where all of our dags are running and connect to that.

**Comment by rajaths010494** [comment]
https://astronomer.slack.com/archives/C01UA03TPV1/p1676284953592199 started a conversation of running the services on containers locally and point the connection to that.

**Comment by sunank200** [comment]
As per the discussion on slack thread; as per discussion on sprint call we should separate this into two setups on astro-cloud. One for databases requires file system (1 worker) and another for databases that can run remotely (multiple workers).

**Comment by rajaths010494** [comment]
Created a deployment for a single worker and modified the deploy script.

**Comment by rajaths010494** [comment]
Moved deployment from astronomer org to astronomer validation and created infra for FTP and SFTP on aws dag authoring account

**Comment by rajaths010494** [comment]
https://galileo.astronomer.io/support/tickets/2457 for new slack channel for alerts

**Comment by sunank200** [comment]
Let's merge this change. We can create another PR to replace slack details.

**Comment by rajaths010494** [comment]
https://astronomer.slack.com/archives/C037VQ1HCHZ/p1676529337129459 multiple worker
https://astronomer.slack.com/archives/C037VQ1HCHZ/p1676529088241279 single worker
