### ISSUE TITLE
Minio support with Snowflake not working

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#1746]
**Describe the bug**
Slack thread - https://astronomer.slack.com/archives/C02B8SPT93K/p1675792250967869

**Comment by utkarsharma2** [comment]
We need to treat the connection for `minio` differently from the one for S3 and add a new file location for `minio`. So that we can avoid going into the native path for S3 and databases.

**Comment by sunank200** [comment]
@sunank200 to sync up with Michael Gregory and understand the issue better.

**Comment by sunank200** [comment]
@sunank200 to sync with @utkarsharma2 for the approach and discussion on slack thread.
