### ISSUE TITLE
Migrate Integration Tests deployment from Astronomer to Astronomer Validation Org in Astro Cloud

### ISSUE THREAD

**Issue by rajaths010494** [astronomer/astro-sdk#1759]
With the organisational efforts to keep Astronomer org only for production workloads, we need to migrate our existing astro-sdk integration tests deployment from Astronomer Org to Astronomer Validation Org.

**Comment by rajaths010494** [comment]
Moved integration tests for astronomer validation org

**Comment by rajaths010494** [comment]
created a server for SFTP and FTP on ec2 in dag-authoring account

**Comment by phanikumv** [comment]
is this done or anything is pending?

**Comment by rajaths010494** [comment]
This can be closed. As discussed in standup will turn off master_dag on astronomer org.
