### ISSUE TITLE
Optimise Redshift Cluster costs

### ISSUE THREAD

**Issue by rajaths010494** [astronomer/astro-sdk#1760]

**Comment by utkarsharma2** [comment]
Steps:
1. Exclude the redshift testcase from CI
2. Create a daily GitHub action to start the cluster, run redshift tests, and close the cluster.

**Comment by rajaths010494** [comment]
https://github.com/astronomer/astro-sdk/pull/1807#pullrequestreview-1316918675

**Comment by rajaths010494** [comment]
on hold currently

**Comment by sunank200** [comment]
Any updates on this task @rajaths010494 . It would be good if you could update the reason why we have kept this task on hold.

**Comment by rajaths010494** [comment]
@sunank200  https://github.com/astronomer/astro-sdk/pull/1807#pullrequestreview-1316918675.

**Comment by pankajkoti** [comment]
I think we can close this issue for now and re-open it if needed later. @sunank200 It was decided that this issue is not a priority at the moment given the efforts needed to tackle it.
