### ISSUE TITLE
Missing Constraints file for Python SDK 1.5.2 and 1.5.1

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#1814]
There's a [constraints file](https://github.com/astronomer/astro-sdk/blob/constraints-1.5.0/constraints-3.9-2.5.1.txt) for Airflow `2.5.1 with SDK `1.5.0`, but not one for Airflow `2.5.1 with SDK `1.5.2`.

**Comment by pgzmnk** [comment]
Thank you, team.

**Comment by phanikumv** [comment]
This is done , constraints for 1.5.1 and 1.5.2 are now available. 

https://github.com/astronomer/astro-sdk/blob/constraints-1.5.1/constraints-3.9-2.5.1.txt
https://github.com/astronomer/astro-sdk/blob/constraints-1.5.2/constraints-3.9-2.5.1.txt

**Comment by pgzmnk** [comment]
This is great! Thank you @phanikumv!
