### ISSUE TITLE
Support for query tags

### ISSUE THREAD

**Issue by dimberman** [astronomer/astro-sdk#1820]
**Please describe the feature you'd like to see**
Snowflake users use query tags to add necessary lineage and governance data to queries. Currently there’s no easy way to use query tags in the astro SDK except to create a unique connection per query-tag. A customer told me that to do this via connections he would need to create ~10 unique connections per team which is not sustainable. 

**Describe the solution you'd like**
We should implement a `query_tags` parameter to the `aql.dataframe`, `aql.transform`, and `aql.run_raw_sql` functions.

```
@aql.dataframe(conn_id='foo', query_tags=['fizz', 'buzz'])
def foo...
```

We can also make this a runtime argument

```
@aql.dataframe(conn_id='foo')
def foo...

with dag:
    foo(query_tags=['fizz','buzz'])
```

**Are there any alternatives to this feature?**
As mentioned the query tag alternative is to create connections for each set of tags.

**Additional context**
Add any other context about the feature request here.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by tatiana** [comment]
@dimberman I think having tags related to queries is a useful feature. Given that the Python SDK tries to expose generic interface cross-databases, do the other databases supported by the Python SDK have a similar concept to `query_tags`?

If more databases have this concept, I believe the proposed interface would be fine (BTW: why would we change `dataframe` and not `transform_file`?)

If Snowflake is the only currently supported database with this concept, it may be worth exposing it in another way.
