### ISSUE TITLE
Add argument: only cleanup if all tasks succeeded

### ISSUE THREAD

**Issue by scottleechua** [astronomer/astro-sdk#1826]
**Please describe the feature you'd like to see**
Right now, `astro.sql.cleanup` deletes temporary tables once upstream tasks are done. However, it does not currently distinguish between upstream tasks finishing because of success vs failure.

I would like `cleanup` to have an optional argument that prevents cleanup if any upstream task fails. This would be useful during DAG development, where I may not want to keep regenerating all temporary tables while bugfixing failing tasks.

**Describe the solution you'd like**
An optional boolean argument to `cleanup` that instructs no cleanup in case of any upstream failure (e.g., `pass_on_failure`).

**Comment by tatiana** [comment]
Thanks, @scottleechua ! I agree the flag `skip_on_failure` would be an excellent addition.

Do you have interest and availability to implement this feature? We could support you in getting up to speed if you'd like to!

Otherwise, we'll add it to a milestone and implement it as soon as possible.

**Comment by scottleechua** [comment]
@tatiana Yep, I'd be glad to contribute! If you could let me know where to look in the codebase, I'll have a look.

(And if you have any guidelines for contributors, too!)

Many thanks 😄

**Comment by tatiana** [comment]
Hi @scottleechua! Thank you very much.

The cleanup operator implementation is mostly in [python-sdk/src/astro/sql/operators/cleanup.py](https://github.com/astronomer/astro-sdk/blob/main/python-sdk/src/astro/sql/operators/cleanup.py#L96-L109)

We'd be introducing `skip_on_failure` in a [similar place](https://github.com/astronomer/astro-sdk/blob/main/python-sdk/src/astro/sql/operators/cleanup.py#L87) to `run_sync_mode`:

Tests are available at:
* [unit tests](https://github.com/astronomer/astro-sdk/blob/main/python-sdk/tests/sql/operators/test_cleanup.py): `python-sdk/tests/sql/operators/test_cleanup.py`
* [integration tests](https://github.com/astronomer/astro-sdk/blob/main/python-sdk/tests_integration/sql/operators/test_cleanup.py): `tests_integration/sql/operators/test_cleanup.py`

There's a [development guide](https://github.com/astronomer/astro-sdk/blob/main/python-sdk/docs/development/DEVELOPMENT.md) and the [contribution guide](https://github.com/astronomer/astro-sdk/blob/main/python-sdk/docs/development/CONTRIBUTING.md).

Please let me know how it goes - there's lots of room to improve our docs, and any feedback is much appreciated!

Also, if you'd like to pair on this, we can do it - London and Singapore are not that far and I'm optimistic we could find a time that would work for both.

**Comment by scottleechua** [comment]
Hi @tatiana ! Opened a PR as above, can continue the conversation there!

While I couldn't get a dev environment running (the `make` commands in the development guide were throwing errors), I could run the `nox` lints and tests just fine. 😄
