### ISSUE TITLE
Propose and document strategy to clean up temporary tables

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#186]
**Context**
Although Astro 0.6.0 records data into temporary tables, it does not offer any tooling for users to clean temporary tables.

**Acceptance criteria**
- Create an [AEP](https://github.com/astro-projects/astro/tree/main/docs/aep) with a proposal of strategy for users to clean temporary tables.
- Have it approved by two other core committers and two team members of the data team.

**Comment by kaxil** [comment]
Closed by https://github.com/astronomer/astro-sdk/issues/436
