### ISSUE TITLE
Write example DAG using Panglia dataset to support Astronomer's official docs

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#188]
**Context**
@jwitz has been writing the official Astronomer documentation at: 
https://github.com/astronomer/docs/pull/477/files

And [he asked us](https://github.com/astronomer/docs/pull/477/files#r822561109) to write a `transform` example using the Panglia dataset.

**Acceptance criteria**
* Create an example DAG which has `transform` and uses the Panglia dataset
* Share it with @jwitz in the Github thread

**Comment by sunank200** [comment]
This is done.
