### ISSUE TITLE
Add an Excel FileType

### ISSUE THREAD

**Issue by skolchin** [astronomer/astro-sdk#1956]
**Please describe the feature you'd like to see**
I believe it'd be really nice to add support of native Excel files loading and saving.

**Describe the solution you'd like**
This would require creation of new `ExcelFileType` class (it would be very similar to `CSVFileType`) and some small modifications in base `File` and `FileType` classes. Also, some Excel processing packages (e.g. `openpyxl`) has to be added to dependencies.

**Are there any alternatives to this feature?**
I have implemented an Excel Airflow hook myself (didn't publish it though), but it's kinda old-style and could be nicely replaced with Astro-SDK Files.

**Additional context**
I have a  particular DWH project where a lot of data exchange is going to be through the Excel files generated by some kind of legacy reporting system. Having native Excel support would definetely help in this case

**Acceptance Criteria**

- [x] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by pankajastro** [comment]
Hi @skolchin would you like to draft a PR since you already have some implementation, we would love to collaborate and get it done.  Thank you!

**Comment by skolchin** [comment]
Yeah, I would try!

**Comment by pankajastro** [comment]
closing it since https://github.com/astronomer/astro-sdk/pull/1978 has merged
