### ISSUE TITLE
Look into CI Failure

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#2056]
PR - https://github.com/astronomer/astro-sdk/pull/2053

**Comment by utkarsharma2** [comment]
Issues found:
1. Snowflake, Databricks, and Azure keys were expired 
2. Snowflake query response is changed, look for the query in test - test_snowflake_create_table_with_columns

**Comment by vatsrahul1001** [comment]
Thanks @utkarsharma2 for looking into this
