### ISSUE TITLE
Create a Makefile with local development commands

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#213]
**Please describe the feature you'd like to see**
At the moment, we expect developers to set up a development environment by manually following the steps described in the document [DEVELOPMENT.md](https://github.com/astro-projects/astro/blob/main/docs/DEVELOPMENT.md). This process is prone to errors. The goal with this ticket is to automate those steps where possible, by having a project `Makefile`.

**Describe the solution you'd like**
Features:
- [x] `make setup`: to create a Python virtual environment and install all the dependencies necessary to this local environment (including Airflow). It should also install pre-commit and download the Postgres docker image. Make a copy of the configuration files (`.env` and `ci-test-connections.yml`), if they don't exist, and prompt the user to update them with their credentials.
- [x] `make tests`: to run all the tests and include coverage using `--cov-branch and --cov-report term-missing`, so the developer can see which lines haven't been covered.
- [x] `make unit_test`: to run all the unit tests, which don't depend on external databases or remote object stores (+ coverage)
- [x] `make integration_tests`: to run all the integration tests, which rely on external databases and/or remote object stores (+ coverage)
- [x] `make snowflake_tests`: to run all the integration tests which use Snowflake and none of the other DBs (+coverage)
- [x] `make postgres_tests`: to run all the integration tests which use Postgres and none of the other DBs (+coverage)
- [x] `make aws_tests`: to run all the integration tests which use S3 and/or Redshift and none of the other DBs (+coverage)
- [x] `make google_tests`: to run all the integration tests which use GCS and/or BigQuery and none of the other DBs (+coverage)
- [x] `make quality`: to run all the quality checks declared within `pre-commit`

**Acceptance Criteria**

- [ ] Have a Makefile that can be run in MacOS and Ubuntu which implements the following features

**Comment by bhavaniravi** [comment]
How to differentiate `unit_test` from `integration_test`?
