### ISSUE TITLE
Release Astro-SDK

### ISSUE THREAD

**Issue by vatsrahul1001** [astronomer/astro-sdk#2170]
We noticed all of Astro-SDK example DAG's were failing with runtime  python3.12. Issue reported: https://github.com/astronomer/issues-airflow/issues/696. This has been fixed in https://github.com/astronomer/astro-sdk/pull/2146. We need to release with this fix

**Comment by Lee-W** [comment]
@utkarsharma2 @vatsrahul1001 it has been released earlier today
