### ISSUE TITLE
Fix - BooleanCheck testcase - test_happyflow_success_with_templated_query

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#219]
Testcase - test_happyflow_success_with_templated_query 
Failing for - bigquery and snowflake

**Comment by kaxil** [comment]
Is this still an issue @utkarsharma2 ?

**Comment by utkarsharma2** [comment]
@kaxil, It's still an issue, I'll check this tomorrow.

**Comment by sunank200** [comment]
This is old ticket not relevant any more.
