### ISSUE TITLE
Refactor suggestions from #232 review

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#245]
* [ ] Change `save_file` to use `astro.utils.get_hook`. From: https://github.com/astro-projects/astro/pull/232#discussion_r835042901
* [ ] Change SQLDecorator to use `read_sql_table`. From: https://github.com/astro-projects/astro/pull/232#discussion_r835051788
* [ ] Remove the method `get_sql_achemy_engine` from the SQLDecorator, using the `utils.database.get_sqlalchemy_engine` instead. From: https://github.com/astro-projects/astro/pull/232#discussion_r835054255
* [ ] Improve the Database detection, potentially using `aenum`. From: https://github.com/astro-projects/astro/pull/232#discussion_r835224383
* [ ] Try to use `astro.sql.table.Table.qualified_name` as opposed to `table_name` when using Sqlalchemy `SqlaTable`, from: https://github.com/astro-projects/astro/pull/232#discussion_r835045376

**Comment by kaxil** [comment]
Closing this but do let me know if we still need to take care of this @tatiana

**Comment by kaxil** [comment]
Closing this but do let me know if we still need to take care of this @tatiana
