### ISSUE TITLE
Enable Pylint

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#278]

**Comment by kaxil** [comment]
Ran the following before (https://github.com/astronomer/astro-sdk/commit/04f309d) and after refactor (commit: https://github.com/astronomer/astro-sdk/commit/f8ddf8b8bc8ce0992ef9b85065e8d2d3e1a9df45)
```
❯ pylint src -r y -f colorized --max-line-length=110
```

**Before refactor**: `Your code has been rated at 6.42/10`
**After refactor**: `Your code has been rated at 8.54/10 (previous run: 6.42/10, +2.12)`

**Comment by feluelle** [comment]
From my experience with Airflow I don't really like pylint 😅. If you want to have a rating for your code, GitHubs native [LGTM](https://lgtm.com/) would be a great option.

**Comment by kaxil** [comment]
That's a good point about LGTM tool

**Comment by feluelle** [comment]
> LGTM.com will be shut down in December 2022 — we recommend that you use GitHub code scanning instead.

Okay then we just use `GitHub code scanning` instead.
