### ISSUE TITLE
Add `__repr__` to all our classes

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#283]
**Reference**:
- https://stackoverflow.com/questions/1436703/what-is-the-difference-between-str-and-repr

Currently, without `__repr__`, if you create an instance of a Database class and print it out, it will give the memory address as shown below.
```python
>>> from astro.databases.snowflake import SnowflakeDatabase
>>> SnowflakeDatabase("d")
<astro.databases.snowflake.SnowflakeDatabase object at 0x7ff3c80afe80>
```

As part of this GitHub issue, we should evaluate all of custom classes (`FileType`, `FileLocation` etc) and add `__repr__` methods wherever they are missing.

Example:

https://github.com/astronomer/astro-sdk/blob/5a511d265c6aed10248a1e36fd986518eaec0875/src/astro/files/base.py#L87-L93

**Comment by dimberman** [comment]
@kaxil should we add this to the operators as well? It seems like the only objects that users would interact with are Database, File, Table, and Metadata.
