### ISSUE TITLE
Try to change Astro Python SDK check example DAGs to use GreatExpecatations

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#302]
**Context**
We've been having discussions about the Astro Python SDK check strategy. It feels there is an overlap with Great Expectations.

As part of this, we created:
1. https://github.com/astro-projects/astro/issues/298
2. https://github.com/astro-projects/astro/issues/301

The idea with this ticket is, once the ticket https://github.com/astro-projects/astro/issues/301 is completed, to change these (check) example DAGs to use the Great Expectations operator.

**Acceptance criteria**
* [ ] Pair with someone who has been involved with the development of the GreatExpectations operator (Benji Lampel?)
* [ ] Have a version of the (check) example DAGs using Great Expectations
* [ ] Based on this experience, propose a way to move forward, documenting the findings

**Comment by kaxil** [comment]
@dimberman To take a look after completing https://github.com/astro-projects/astro/pull/322

**Comment by tatiana** [comment]
@utkarsharma2 has led a new work stream on data validation; this ticket needs to be updated. We can create new ones in future as needed.
