### ISSUE TITLE
Create BigqueryDatabase without file operations

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#331]
**Describe the context**
This task is part of the [Astro Python SDK refactor]().

Similar module: https://github.com/astro-projects/astro/blob/main/src/astro/databases/sqlite.py

**Acceptance criteria**
* [ ] Create `BigqueryDatabase`, implementing all the necessary methods except for `load_file_to_table` and `export_table_to_file`.
* [ ] All the quality checks passed
* [ ] All the functions have typehints
* [ ] All the new functions and modules have docstrings
* [ ] The introduced code has 100% of test coverage

**Comment by kaxil** [comment]
The only thing missing is `append/merge`

**Comment by kaxil** [comment]
closing this in favor of https://github.com/astronomer/astro-sdk/issues/343
