### ISSUE TITLE
 Refactor the `dataframe` operator

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#348]
**Describe the context**
This task is part of the [Astro Python SDK refactor]().

**Dependencies**
* Depends on: #344

**Acceptance criteria**
* [ ] Implement the `dataframe` operator using the new `Database` class and using the `create_database(conn_id)` function and the refactored base operator.
* [ ] All the quality checks passed
* [ ] All the functions have type hints
* [ ] All the new functions and modules have docstrings
* [ ] The introduced code has 100% of test coverage
* [ ] Rename the module/tests: https://github.com/astronomer/astro-sdk/pull/373/files#r878707527

**Comment by kaxil** [comment]
closed by https://github.com/astronomer/astro-sdk/pull/391
