### ISSUE TITLE
output_table parameter for aql.loadfile should be optional

### ISSUE THREAD

**Issue by mikeshwe** [astronomer/astro-sdk#365]
**Describe the bug**

currently, you have to specify:

        output_table=Table(database=SNOWFLAKE_DATABASE,conn_id=SNOWFLAKE_CONN_ID)

even if the database is specified in the conn_id.

**Version**
* Astro: astro-projects==0.8.2
* OS: macOS

**Expected behavior**
We should be able to specify:

        output_table=Table(conn_id=SNOWFLAKE_CONN_ID)

**Screenshots**
![Screen Shot 2022-05-17 at 2 52 16 PM](https://user-images.githubusercontent.com/4237498/168916281-04cf6b59-a807-41f9-96e6-92c42fce07be.png)

**Comment by mikeshwe** [comment]
Same for: 

`customers_table = Table(table_name=SNOWFLAKE_CUSTOMERS,conn_id=SNOWFLAKE_CONN_ID,database=SNOWFLAKE_DATABASE)`

Should be:

`customers_table = Table(table_name=SNOWFLAKE_CUSTOMERS,conn_id=SNOWFLAKE_CONN_ID)`

**Comment by tatiana** [comment]
@mikeshwe, this will likely be solved once we merge:
https://github.com/astronomer/astro-sdk/pull/360

**Comment by kaxil** [comment]
closed by https://github.com/astronomer/astro-sdk/pull/360
