### ISSUE TITLE
load_file should have a file parameter instead of a path and file_conn_id

### ISSUE THREAD

**Issue by mikeshwe** [astronomer/astro-sdk#366]
**Please describe the feature you'd like to see**        

instead of:

foo = aql.loadfile (
        path=S3_FILE_PATH + '/orders_data_header.csv',
        file_conn_id=S3_CONN_ID,
       ...
)

**Describe the solution you'd like**

foo = aql.loadfile (
        file = File(S3_FILE_PATH +'/orders_data_header.csv',S3_CONN_ID),
       ...
)

**Are there any alternatives to this feature?**
Is there another way we could solve this problem or enable this use-case?

**Additional context**
Add any other context about the feature request here.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astro-projects/astro/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by tatiana** [comment]
@mikeshwe, this will likely be solved once we merge https://github.com/astronomer/astro-sdk/pull/360

**Comment by tatiana** [comment]
This was closed by: https://github.com/astronomer/astro-sdk/pull/360
