### ISSUE TITLE
load_file operator silently fails if the local file is not existing

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#467]
**Describe the bug**
When we use the load_file operator and pass a local file and the file doesn't exist, the operator does nothing and fails silently. 

**Version**
* Astro: [e.g. 0.9.2]

**To Reproduce**
1. Use the load_file operator:
    ```
     aql.load_file(  # noqa: F841
            input_file=File(
                path='/tmp/non_existing_file.csv',
            ),
            task_id="load_csv",
            output_table=table_metadata,
            chunk_size=chunk_size,
     )
    ```
2. Now the operator will run without any warning or failure making the user think that the operator ran successfully.

**Expected behavior**
**Case 1 (default)**

> The operator should fail with an error if param `if_file_doesnt_exist`  is set to `exception` saying that the file doesn't exist.

**Case 2**

> if the `if_file_doesnt_exist` is set to `suppress` the operator should not raise an exception.

To accommodate this behaviour added a parameter `if_file_doesnt_exist`  to `load_file()` operator and `get_file()` function.

**Comment by kaxil** [comment]
@utkarsharma2 this can be closed, right?

can you comment which PR closed it plz

**Comment by kaxil** [comment]
closes https://github.com/astronomer/astro-sdk/pull/476
