### ISSUE TITLE
Implement `get_file_list` (Dynamic Task Templates)

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#507]
This builds on top of [Dynamic Tasks Mapping](https://airflow.apache.org/docs/apache-airflow/2.3.0/concepts/dynamic-task-mapping.html) released in Airflow 2.3

Iterating over a set of files matching a pattern in a file system:
- Look for all files matching a pattern in a file system such as S3 
- And then, to iterate over a set of tasks for each file found matching this pattern. 
- Again, the number of files found is unknown at DAG creation time, but it is not uncommon for this to be dozens of files. 

The `get_file_list` operation would abstract away the underlying Operator setup and boilerplate code, similar to the existing `load_file` operation in the Astro Python SDK. It would then get back a list of files suitable for the ensuing “map” operation. 

The idea here is to minimize the “boiler plate” code which needs to be written by a DAG Author and to institutionalize common patterns. Effectively, the above when coupled with a TaskGroup which works on each value represents the FileIterator pattern for DAG Authoring.

**Comment by pankajastro** [comment]
initial investigation: https://docs.google.com/document/d/1qaxJ5cP7Cu_lVMDIUMWEYoDdDt63PpISWczqTwBcjXo/edit?usp=sharing

**Comment by utkarsharma2** [comment]
@pankajastro We already have similar method - https://github.com/astronomer/astro-sdk/blob/b77e22e27ad60aa86073b59bcf37ac942e355981/src/astro/files/base.py#L99

**Comment by pankajastro** [comment]
> @pankajastro We already have similar method -
> 
> https://github.com/astronomer/astro-sdk/blob/b77e22e27ad60aa86073b59bcf37ac942e355981/src/astro/files/base.py#L99

thanks @utkarsharma2 I'll take a look and try to use it

**Comment by pankajastro** [comment]
Leveraging  `create_file_location` from  `astro.files.locations` to get the location type and then getting `paths` property on the location. currently, it is expected that the user will pass path and pattern in a single param `path` for example in the case of a local filesystem if I want to list all CSV files which inside the logs folder I'll do something like `dtt.get_file_list('conn', logs/*.csv)`
