### ISSUE TITLE
Onboarding Pankaj to the team

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#508]
Sending the links and references in a DM/Email.

**Dynamic Task Mapping**:
- [Ash's talk at Airflow Summit](https://youtu.be/P6sqdPr7h1M)
- [Astronomer Video](https://www.youtube.com/watch?v=elBv6wROKpw)
- [Astronomer Guide](https://www.astronomer.io/guides/dynamic-tasks/)
- [Airflow docs](https://airflow.apache.org/docs/apache-airflow/2.3.0/concepts/dynamic-task-mapping.html)
- [Marc's blog post](https://marclamberti.com/blog/dynamic-task-mapping-in-apache-airflow/)
- [AIP-42](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-42+Dynamic+Task+Mapping)

**Comment by pankajastro** [comment]
Gone through the above documentation.
