### ISSUE TITLE
Nuke AWS and GCP unused resources

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#533]
**Please describe the feature you'd like to see**
Currently, we let resources run on Cloud Platforms even when they are unused. 

**Describe the solution you'd like**
We can have periodic jobs that can nuke that unused resource.

**Acceptance Criteria**
- [ ] Improve the documentation (README, Sphinx, and any other relevant)

**Comment by sunank200** [comment]
This is old ticket not relevant any more.
