### ISSUE TITLE
Cut 1.0.0b1

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#551]
**Acceptance criteria**
* [X] Check that the docs are still working (including `README.md` and "tutorial")
* [X] Write release notes
* [ ] Release
* [ ] Inform Mike so we can collect users' feedback
* [ ] Inform the Data team
* [ ] Inform the Astro Build team

**Comment by utkarsharma2** [comment]
Varified README.md dag - working fine

**Comment by utkarsharma2** [comment]
Verified GETTING_STARTED.md with main branch - Working fine
commit https://github.com/astronomer/astro-sdk/commit/461e63e7a2ef1c8bb17fda4c9752d0bca942d538

**Comment by utkarsharma2** [comment]
Added branch - https://github.com/astronomer/astro-sdk/tree/1.0.0b1
