### ISSUE TITLE
Propose how the SQL SDK will co-exist with the Python SDK

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#552]
**Acceptance criteria**
* [ ] Propose how the repo will look like
* [ ] Propose how this affects the CI
* [ ] Propose how this affects doc build
* [ ] Propose how this affects the issue tracking

Suggestion: check the following projects:
* apache/beam
* kubernetes/kubernetes
* google cloud (?) - check if it still exists
* apache/airflow

**Comment by kaxil** [comment]
@dimberman as a follow of this, do you want to start moving files around so that we have a mono-repo and you and SQL SDK team can start working on it
