### ISSUE TITLE
Include File size and File type in native path selection logic

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#573]
**Please describe the feature you'd like to see**
Currently, we are only using Source and Destination to determine the transfer logic to be executed - default path / native path.
There are issues with this approach
1. File Types - We are assuming the native transfer is supported for all file types. This is not the case with Snowflake and Bigquey.
2. File Size - When transferring data from the S3 to Bigquery, we create a Data Transfer Job in Biquery. Which is overkill for the smaller files. 
       
**Describe the solution you'd like**
When we include the File Type and File Size in the decision to select a native or default path. We can better select the path which can lead to a better user experience and faster transfer.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by sunank200** [comment]
We have implemented 1. (File Types - We are assuming the native transfer is supported for all file types. This is not the case with Snowflake and Bigquey. ) already. We can close this and consider later if this is reported by user.
