### ISSUE TITLE
Unable to use standard Google conn_id for aql.load_file into BigQuery

### ISSUE THREAD

**Issue by TheCodyRich** [astronomer/astro-sdk#603]
**Describe the bug**
When using aql.load_file to load data from GCS to BQ, task fails due to authentication error.  The GCSToBigQueryOperator is able to run successfully using the Google Cloud Platform connection, however the astro sdk does not.  I was able to get the astro sdk task to run successfully by adding `RUN curl -sSL https://sdk.cloud.google.com | bash` to the docker file then manually authenticating in the docker container and running `gcloud auth application-default login` (i.e. not using the conn_id).

**Version**
* Astro SDK 0.11.0
* Astro CLI 1.02
* Astro run-time 5.0.6

**To Reproduce**
1. Create a google cloud connection utilizing the connection type, "Google Cloud Platform" (Figure 1).  Message me for connection details
2. Run attached DAG as is with connection details provided by me, or if using your own connection details update paths, schemas,  and variables to reflect your own data and connections
3. See the astro sdk task fails due to an auth error while the GCSToBigQueryOperator tasks run successfully (Figure 2)

**Expected behavior**
astro sdk should be able to authenticate to Google BigQuery by providing the Google Cloud Platform connection id using the conn_id `google_cloud_default`

**Screenshots**

Figure 1: Google Cloud connection
![image](https://user-images.githubusercontent.com/83995939/182436367-7d643086-b12e-4f2d-8cd3-02a71c65fd58.png)

Figure 2: astro sdk task fails (due to auth error) with GCS BQ operators succeed.
![image](https://user-images.githubusercontent.com/83995939/182443928-5564665f-066b-473a-a06c-0dd87a5f2e22.png)

**Additional context**
[Full logs from the astro sdk task (gcs_to_bq_sdk)](https://github.com/astronomer/astro-sdk/files/9244653/Task_Instance__gcs_to_bq_sdk.log)

[test DAG](https://github.com/astronomer/astro-sdk/files/9244666/astro_sdk_bq_test.py.zip)

**Comment by feluelle** [comment]
Hey @TheCodyRich,

I have managed to fix your issue in #668, I believe. At least I have tested it with your connection details and it worked.

To test it with your astro stack, do the following:

Edit your `requirements.txt` to install from my branch:
```txt
https://github.com/astronomer/astro-sdk/archive/feature/enable-google-cloud-service-account-authentication.zip
```

I had access reaching the `Compute Engine Metadata server` if I don't set the `GOOGLE_APPLICATION_CREDENTIALS` env var. So make sure to add your `keyfile` to the `include` folder and edit your `.env` like so:
```env
GOOGLE_APPLICATION_CREDENTIALS=/usr/local/airflow/include/keyfile.json
```
