### ISSUE TITLE
Map File & Table classes to Datasets (AIP-48)

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#611]
There will be an alpha build of 2.4 very soon (Sync with the Ash/Jed to get the tag), so to make sure Python SDK can use 2.4 dataset feature (and allows viewing dataset dependency in UI), let's map the File and Table to AIP-48 datasets to show dependencies between tasks and Dags.

**Comment by kaxil** [comment]
Astro Runtime `6.0.0-alpha1` image is out where I will do the mapping

**Comment by kaxil** [comment]
WIP branch at https://github.com/astronomer/astro-sdk/compare/main...aip-48-mapping

**Comment by kaxil** [comment]
Both Table and File object have been mapped with 6.0 alpha2 runtime image but the code needs to be cleaned up

**Comment by kaxil** [comment]
Pending items:

- [ ] Add inlets and outlets on all operators
- [ ] Add docs

**Comment by pankajkoti** [comment]
PR is in review and @utkarsharma2 is going to review it. Potentially merge it if looks all good today.

**Comment by kaxil** [comment]
Another PR: https://github.com/astronomer/astro-sdk/pull/808

Only doc PR is pending now

**Comment by kaxil** [comment]
I will create separate task for docs so that I can close this out
