### ISSUE TITLE
File object should work event without filetype param

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astro-sdk#644]
**Describe the bug**
If I'm passing a folder path URI in File object it throws error 

```
Broken DAG: [/usr/local/airflow/dags/task_flow.py] Traceback (most recent call last):
  File "/usr/local/airflow/astro_sdk/src/astro/files/types/__init__.py", line 25, in create_file_type
    filetype = get_filetype(path)
  File "/usr/local/airflow/astro_sdk/src/astro/files/types/__init__.py", line 53, in get_filetype
    raise ValueError(
ValueError: Missing file extension, cannot automatically determine filetype from path 'gs://pankaj_test_dtt/'. Please pass the 'filetype' param with the explicit filetype (e.g. csv, ndjson, etc.).
```

**Version**
* Astro: [e.g. 0.6.0]
* OS: [eg. Debian]

**To Reproduce**
1. Write the DAG  '...'
2. Create connection '....'
3. Run using  '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pankajastro** [comment]
Discussion: https://github.com/astronomer/astro-sdk/pull/596#discussion_r943415100

**Comment by utkarsharma2** [comment]
duplicate https://github.com/astronomer/astro-sdk/issues/644
