### ISSUE TITLE
Clean up current documentation/ quickstarts

### ISSUE THREAD

**Issue by jwitz** [astronomer/astro-sdk#652]
**Describe the bug**

I'm planning to update the existing `GETTING_STARTED` guide and `README` to be in line with general Astro documentation best practices. I'll open up issues in the future for further doc improvements, but getting these docs in good shape is my main priority for the initial release. Let me know if there's any other docs I should be working on!

**Additional context**

**Comment by feluelle** [comment]
I have assigned the issue to you @jwitz as I think you have already started on it, correct?
