### ISSUE TITLE
[SPIKE] Data Validation support

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#655]
Create tasks based on the outcome of this SPIKE.

**Comment by utkarsharma2** [comment]
@kaxil do we want to reintroduce the validation checks we had earlier, in 0.8.4 release - https://github.com/astronomer/astro-sdk/issues. 
1. Aggregate_check.py
2. Boolean_check.py
3. stats_check.py

or/and explore other options?

**Comment by kaxil** [comment]
We want to explore some more options - a) Build some of our own validation checks that are simple to use. b) Can we hook into allowing Validations via Great Expectation and/or Soda SQL too.

Talk to @mikeshwe on the feedback he received from customers.

**Comment by kaxil** [comment]
@utkarsharma2 Worth checking https://www.astronomer.io/guides/airflow-sql-data-quality-tutorial/ too when you start your research

**Comment by phanikumv** [comment]
@utkarsharma2 to create separate stories in case needed, based on the analysis done so far.

**Comment by denimalpaca** [comment]
Hey - would like to put a note here about including OpenLineage integration as part of this. There's a blog post I wrote [here](https://openlineage.io/blog/operators-and-extractors-technical-deep-dive/) describing the relationship between operators and extractors. They key idea for data quality operators like the ones in the above guide is that they need to save state about a few things in the quality checks:
- The check name
- The check type (for column checks)
- The success or failure of the check
- The value returned by the check
OpenLineage also requires a query for checks run on a database that it will display in the UI.
