### ISSUE TITLE
Document how to add support for new Database

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#682]
Based on the experience of building support for a new DB, we should add dev docs on how to do it so it is easier for a new joiner in the team to know the process

**Comment by kaxil** [comment]
How is this progressing @pankajkoti ?

**Comment by pankajkoti** [comment]
Hi @kaxil. I had planned to work on this today at the start of the week. I ran into a few blockers for the benchmarking script for Redshift db performance and still facing some issues. Utkarsh and Tatiana paired up with me initially but there are still some issues in the script and would need more time on it.

@phanikumv also reminded me to work on this one with priority in this week. So was planning to work on the document after the benchmarking task. 

One question I had is where should we publish this document? Github repo ReadMe, Notion doc, Google doc, RTFD or some other place? 

I realise and understand that there has been delay on the document from my side. Is it okay if I pick up this after the benchmarking task? If not, I will try if I can work on this earlier.

**Comment by kaxil** [comment]
No worries at all, was just curious.

Yeah benchmarking should be done before this task.

The docs should go in our Contributing.rst file

**Comment by pankajkoti** [comment]
Also mention that benchmark results should be added whenever we add new database. And test the performance well.

**Comment by pankajkoti** [comment]
Made good progress on the document, PR will be ready in a while. ETA 2 PM IST today.
