### ISSUE TITLE
Expose `delimiter` parameter for file object for S3/GCS pattern matching 

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#690]
**Please describe the feature you'd like to see**
Currently, we are not exposing the `delimiter` parameter for pattern resolution for S3 and GCS file locations. Which significantly limits the use of external files.

**Describe the solution you'd like**
Expose a `delimiter` which then is passed to the upstream API calls.

**Additional context**
Add any other context about the feature request here.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Add an example in docs with the usage

**Comment by kaxil** [comment]
Can we use / repurpose the "filetype" arg we have for that? thoughts?

**Comment by phanikumv** [comment]
This is not required anymore as discussed with the team. Hence closing for now.
