### ISSUE TITLE
Use native paths pattern support

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#708]
**Please describe the feature you'd like to see**
Currently, in `load_file()` the algorithm to resolve patterns in paths

1. Resolve patterns in the paths, get all the files that fit the pattern
2. iterate over each file from the file list
3. Perform transfer - native/dataframe

Ref: https://github.com/astronomer/astro-sdk/blob/f00c4b5386b825c143b52dd1ea6ab002ddb6a6c0/src/astro/databases/base.py#L322

**Describe the solution you'd like**
many native transfers support the patterns - it is be better to use the native support to load multiple files as opposed above algo.

1. Explore Databases for pattern support
2. Check if the file path passed has a pattern
3. if pattern is passed and database support pattern, use native support for pattern

**Acceptance Criteria**
- [x] All checks and tests in the CI should pass
- [x] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [x] Integration tests (if the feature relates to a new database or external service)
- [x] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [x] Exception handling in case of errors
- [x] Logging (are we exposing useful information to the user? e.g. source and destination)
- [x] Improve the documentation (README, Sphinx, and any other relevant)
- [x] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by pankajkoti** [comment]
@sunank200 worked on GCS for this and PR will be ready today.

How to resolve schema is a question though. Need to check if we have to create a table for certain databases & also need to check if schema auto-detection works for all supported file types & for file patterns approach.

**Comment by utkarsharma2** [comment]
@sunank200 can you add points from yesterday's discussion here?

**Comment by sunank200** [comment]
<img width="989" alt="Screenshot 2022-09-09 at 5 28 52 PM" src="https://user-images.githubusercontent.com/8670962/189342655-89d5017b-d0c2-4ce1-b9e1-aec4697e3eb1.png">
This is the flow to be checked.

**Comment by pankajkoti** [comment]
Felix's PR which was needed for this is merged now. However, with Felix's [PR](https://github.com/astronomer/astro-sdk/pull/780), we also need to take care of the double-loading in the a separate PR. @utkarsharma2 can you please create a ticket for that?
