### ISSUE TITLE
Use native autodetect schema

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#709]
**Please describe the feature you'd like to see**
Currently, If the user does not specify the table columns property, we currently use pandas to autodetect the table column types automatically. This can sometimes lead to a mismatch in type inferred by pandas and one that the database expects.

**Describe the solution you'd like**
We can let the database infer schema when it is supported by the database and if it is use native support this reduces the chances of mismatch.

**Acceptance Criteria**
- [ ] Use native autodetection for Redshift, BQ, and Snowflake 
- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of the methods, classes, functions, and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by tatiana** [comment]
@utkarsharma2 It may be worth detailing a bit more:
> Currently, we are using pandas to create tables based on files passed. 

To something like:
> If the user does not specify the table columns property, we currently use pandas to autodetect the table column types automatically.

Is the acceptance criteria for this ticket to use native autodetection for all databases (Redshift, BQ and Snowflake)?

**Comment by utkarsharma2** [comment]
@tatiana @feluelle This ticket is an alternative to pandas schema detection. But for a specific case. So the decision tree will be something like this:
```
user-provided schema?
Yes: Use is to create a table
No -
     - Are we using the native path?
          - Yes
              - does the destination database provide schema detection?
                  - Yes: Use native autodetect
                  - No: Use pandas
          - No: Use pandas
```

**Comment by utkarsharma2** [comment]
@sunank200 and I consolidated the databases that support auto-detection: 

<p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" id="docs-internal-guid-b6bfdb67-7fff-8208-3b48-57422f7cb3cf"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Location - GCS</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

Databases/Features | Pattern Resolution | Schema Autodetect
-- | -- | --
Bigquery | Wildcard - * is supportedexample - gs://mybucket/fed-samples/fed-sample*gs://mybucket/fed-samples/fed-sample/*.csv  - only list .csv filesgs://mybucket/fed-samples/fed-sample*.csvPrefix - check! https://cloud.google.com/bigquery/docs/batch-loading-data | Yes
Snowflake | Load files from a table’s stage into the table, using pattern matching to only load data from compressed CSV files in any path:copy into mytable  file_format = (type = 'CSV')  pattern='.*/.*/.*[.]csv[.]gz';Where .* is interpreted as “zero or more occurrences of any character.” The square brackets escape the period character (.) that precedes a file extension.Load files from a table stage into the table using pattern matching to only load uncompressed CSV files whose names include the string sales:copy into mytable  file_format = (format_name = myformat)  pattern='.*sales.*[.]csv';Read more at: https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#loading-using-pattern-matching | Autodetect schema exists only for Parquet ,  Apache Avro, and ORC files.Read more at: https://docs.snowflake.com/en/sql-reference/functions/infer_schema.html

</div>


<p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" id="docs-internal-guid-be66de2b-7fff-427d-03e9-3b1f23b30746"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Location - S3</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

Databases/Features | Pattern Resolution | Schema Autodetect
-- | -- | --
Bigquery | Wildcard support - s3://bucket/*.csvPrefix - check! https://cloud.google.com/bigquery/docs/s3-transfer-parameters | "autodetect": True,missing
Snowflake | TBDLoad files from a table’s stage into the table, using pattern matching to only load data from compressed CSV files in any path:copy into mytable  file_format = (type = 'CSV')  pattern='.*/.*/.*[.]csv[.]gz';Where .* is interpreted as “zero or more occurrences of any character.” The square brackets escape the period character (.) that precedes a file extension.Load files from a table stage into the table using pattern matching to only load uncompressed CSV files whose names include the string sales:copy into mytable  file_format = (format_name = myformat)  pattern='.*sales.*[.]csv';Read more at: https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#loading-using-pattern-matching | TBDAutodetect schema exists only for Parquet ,  Apache Avro, and ORC files.Read more at: https://docs.snowflake.com/en/sql-reference/functions/infer_schema.html

</div>

**Comment by feluelle** [comment]
@utkarsharma2 for bigquery I don't see how we can make it work for "Location - S3". There is no autodetect or similar option in bigquery datatransfer [config](https://cloud.google.com/python/docs/reference/bigquerydatatransfer/latest/google.cloud.bigquery_datatransfer_v1.types.TransferConfig).

For gcs to bigquery we are already using `autodetect`.

**Comment by utkarsharma2** [comment]
@feluelle I think we can skip it for S3 to bigquery? 

Also, I think we are doing this for GCS and Bigquey in Bigquery's `load_gs_file_to_table()` method. Which is not really used since the table is already created. I have created PR for removing this - https://github.com/astronomer/astro-sdk/pull/796

**Comment by utkarsharma2** [comment]
@feluelle can you please add points/contracts from yesterday's discussion here?

**Comment by feluelle** [comment]
> @feluelle I think we can skip it for S3 to bigquery?

Yes, if it is not available yet. 👍 

> Also, I think we are doing this for GCS and Bigquey in Bigquery's load_gs_file_to_table() method. Which is not really used since the table is already created. I have created a PR for removing this - https://github.com/astronomer/astro-sdk/pull/796 So that we can move it to create_table method in this PR.

Great. I have implemented it in the PR now.

**Comment by feluelle** [comment]
> @feluelle can you please add points/contracts from yesterday's discussion here?

Which points are you referring to? Do you mean the pattern resolution in conjunction with autodetect schema? I think it should be clear that these are different features independent of each other.
