### ISSUE TITLE
When passing pattern to "File" object filetype param doesn't make sense

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#749]
**Please describe the feature you'd like to see**
If we pass pattern to a create a file object it may or may not have an extension in it
example -
`File(path="S3://tmp/")` - this won't work right now. Since it's mandatory to have a `filetype` param if the extensions is not specified in `path`

`filetype` param should not be mandatory, because a user can pass a folder path as well.

**Describe the solution you'd like**
When defining the file operator we should first try to resolve the location and then assign and then try to evaluate the file type.

**Additional context**
Add any other context about the feature request here.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by pankajastro** [comment]
possible duplicate https://github.com/astronomer/astro-sdk/issues/644

**Comment by sunank200** [comment]
Yes, @pankajastro. I am working on this

**Comment by sunank200** [comment]
@utkarsharma2 I feel we need file type to be passed from the user's side in case of pattern or folder. 

What would be the filetype when the user passes a folder with both CSV and parquet file or other types as well?

**Comment by tatiana** [comment]
I'm coming late to this discussion, so I'm probably out of context. Since the ticket is still open, however, I'll share my thoughts :)

I don't think we should support folders which contain a mixture of file types. What would be the use case for this?

My impression is that it also introduces more overhead and complexity without a clear benefit.

**Comment by utkarsharma2** [comment]
@tatiana I agree, we are planning to address this by introducing glob patterns. So the user is in full control and filters out all the files he doesn't wish to load into a table. 

Example - 
S3 bucket has following files

s3://tmp/test.csv
s3://tmp/test2.csv
s3://tmp/test3.ndjson

So if the user only wants to process .csv files can do something like this:

`load_file(input_file="s3://tmp/*.csv")`

**Comment by tatiana** [comment]
@utkarsharma2 it's not clear to me that having different file types in the folder is a common use case in the industry/production. I believe the data tends to be homogeneous within the same directory.

It is also not clear to me why we need to remove the `FileType` in the case the user passed `load_file(File(path="s3://tmp/*.csv"))`. Since in this scenario there is an extension, we wouldn't need to fall back to the `FileType` anyway.

**Comment by phanikumv** [comment]
Removed from 1.1.0 as discussed with team.

**Comment by utkarsharma2** [comment]
@kaxil @sunank200  and I concluded the following:

1. We don't need this for milestone 1.1.0. Since we no longer require PR - https://github.com/astronomer/astro-sdk/pull/751 for 1.1.0
2. We will drop support for inferring file types from the extension. This means the parameter `filetype` is mandatory.
3. The final approach for the load_file operator is:
     The file object will have two params
 
     1. path - which will accept glob patterns and will be used to filter the files.
     2. filetype - which will accept constant file types support and will be used to infer the format of the file.
   
        For example, if some buckets have the following content:
        s3://tmp/test1.csv
        s3://tmp/test2.csv
        s3://tmp/test1.data
        
        Case 1:
        load_file(
          input_file=File(path="s3://tmp/test.*csv", filetype=FileType.CSV)
        )
        Files that qualify the filter "s3://tmp/test.*csv" will be
         s3://tmp/test1.csv
         s3://tmp/test2.csv
        and will be treated as a CSV file.
       
       Case 2:
        load_file(
          input_file=File(path="s3://tmp/test.*", filetype=FileType.CSV)
        )
        Files that qualify the filter "s3://tmp/test.*" will be:
         s3://tmp/test1.csv
         s3://tmp/test2.csv
         s3://tmp/test1.data
       and will be treated as a CSV file.
       
       Note - in the second case it's the user's responsibility to make sure the .data file has CSV content.

**Comment by sunank200** [comment]
Closing this as discussed with @kaxil and @utkarsharma2 . This would be breaking change to remove `filetype`.
