### ISSUE TITLE
Create E2E DAG examples

### ISSUE THREAD

**Issue by dimberman** [astronomer/astro-sdk#75]
Acceptance criteria:

Create a series of working and runnable example DAGs that can introduce users to astro with:

1. Snowflake
2. GCP
3. AWS
4. Non-task API DAGs (mixing in traditional operators)
5. With the render function
6. With the append function

**Comment by kaxil** [comment]
What things are pending in this Epic @utkarsharma2 @tatiana ?

**Comment by tatiana** [comment]
@kaxil I believe the AWS exampleis missing, showing the usage of S3 and Redshift (which is not supported yet)

**Comment by sunank200** [comment]
This ticket is done and can be closed now.
