### ISSUE TITLE
Pre-Install astro-sdk-python in Runtime image

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#757]
If you're the kind of org that won't allow xcom pickling for security reasons
1) Can you override that env var back?
2) If Astro SDK is bundled into the image and someone tries to use it, will the task gracefully fail?

**Comment by pankajkoti** [comment]
@kaxil do we need this in 1.1.0 ?

**Comment by kaxil** [comment]
Not a blocker, I want to target it for 1.1.0 if after our tests we are confident, if not we will move it to 1.2

**Comment by pankajastro** [comment]
PR: https://github.com/astronomer/astro-runtime/pull/388

**Comment by phanikumv** [comment]
Included in astro-runtime 7.2, and we need to test it out.

**Comment by pankajastro** [comment]
Tested it, and it is preinstalled in 7.2.0

**Comment by rajaths010494** [comment]
its already been included in runtime image 7.2.0
