### ISSUE TITLE
Support for Python 3.10 with Astro Python SDK

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#760]
I think we do support Py 3.10 for Astro Python SDK -- but we should officially test it out and add a test in CI

**Comment by pankajastro** [comment]
Look like currently we run tests in Python3.8 env only. I was thinking to enable test for other Python versions too but CI time will increase drastically.

**Comment by pankajastro** [comment]
for now, as discussed we are putting this on hold cc: @phanikumv

**Comment by pankajastro** [comment]
Since now we have some separation between unit and integration tests and units tests take relatively less time so I have started on it.  We will run unit tests for Python-{3.8,3.9,10}
