### ISSUE TITLE
Set a configurable limit to run_raw_sql rows output

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#791]
**Context**
By default, `aql.run_raw_sql` does not limit the number of rows it can return.

[Comment on commit](https://github.com/astronomer/astro-sdk/commit/5b93df870dac5787dc1ec4ff11f238b9c360ebb0#r83305025)

**Version**
* Astro: 1.0.2

**Acceptance criteria**

* [x] Have an Airflow config "astro_sdk.run_raw_sql_limit_rows" which allows users to limit the amount of rows returned when running `run_raw_sql`
* [x] Set the default value not to be limited
* [x] Raise a warning if unlimited, explaining the risks to the user

**Comment by pankajkoti** [comment]
This will need a breaking change and hence for now, we will add a warning.
