### ISSUE TITLE
Analyze methods for parsing a SQL directory as a DAG

### ISSUE THREAD

**Issue by dimberman** [astronomer/astro-sdk#794]
**Please describe the feature you'd like to see**
To create a SQL CLI, we need to offer SQL as a native integration into Airflow. This would mean having a system where a SQL engineer can create a directory of SQL files and have Airflow automatically turn the output into a DAG. We can assume that the SQL tasks are in individual files and use a similar templating scheme to the astro python-sdk to communicate inheritance.

**Describe the solution you'd like**
The solution we'd like to see would involve the following UX

1. SQL engineers should not need to know that there is an Airflow DAG being generated (and should have minimal exposure to airflow overall
2. Should be easy for data engineers to deploy and manage in their airflow cluster
3. Should not lead to any speed degradation

**Are there any alternatives to this feature?**
None I can think of

**Additional context**

No
**Acceptance Criteria**

- [x] Create a document that compares different methods of parsing a SQL directory into an airflow readable DAG
- [x] Document should compare pros and cons of rendering the DAG at parse time vs. compiling the directory into a python-sdk DAG that is airflow readable
- [ ] Result of document should lead to an AEP

**Comment by tatiana** [comment]
As part of this task, we are aware of at least two strategies:
* Create a DAG file which has all the tasks expanded (e.g. multiple `aql.transform` statements)
* Create a DAG file which has an operator which points to a SQL directory (e.g. `aql.render`), similar to the prototype implemented in the past: https://github.com/astronomer/astro-sdk/blob/0.8.4/src/astro/sql/parsers/sql_directory_parser.py

We expect this ticket to be considering the pros and cons of at least these two approaches.

**Comment by feluelle** [comment]
Similar to
> Create a DAG file which has all the tasks expanded (e.g. multiple aql.transform statements)

we can use multiple `aql.transform_file` statements

**Comment by feluelle** [comment]
[Doc](https://www.notion.so/Parsing-a-SQL-directory-as-a-DAG-876112c7646349fdb09c654711d38328) available comparing the three methods with Pros and Cons for each of them.

**Comment by tatiana** [comment]
We're only missing the AEP
