### ISSUE TITLE
load_file() can handle pattern in file paths which is not explicit in document

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#800]
**Please describe the feature you'd like to see**
Currently, the feature of load_file() to handle patterns in the path is not clearly mentioned in the documentation and would be worth mentioning explicitly.

**Describe the solution you'd like**
Add a section covering the pattern resolution feature in the load_file() operator.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by utkarsharma2** [comment]
cc: @mikeshwe

**Comment by phanikumv** [comment]
Lets do this by 1.2.1
