### ISSUE TITLE
aql.dataframe does not tolerate empty datafames

### ISSUE THREAD

**Issue by rossturk** [astronomer/astro-sdk#810]
**Describe the bug**
When using `aql.dataframe()` I noticed that it does not gracefully tolerate functions that return an empty dataframe.

**Version**
* Astro: 1.0.2
* OS: Debian 11

**To Reproduce**

1. Run this DAG:

```
CONN_ID = "dwh"

@aql.dataframe
def get_empty_dataframe():
    zilch = []
    return pd.DataFrame(zilch)

with DAG(
    "empty-dataframe",
    schedule_interval="@daily",
    start_date=datetime(2022, 8, 1),
) as dag:
    dataframe = get_empty_dataframe(
        output_table=Table(
            conn_id=CONN_ID,
        )
    )

    aql.cleanup()
```

2. See the resulting error:

```
[2022-09-09T03:05:08.615+0000] {standard_task_runner.py:92} ERROR - Failed to execute job 8277 for task get_empty_dataframe ((snowflake.connector.errors.ProgrammingError) 001003 (42000): 01a6d839-0605-617c-0000-68210fdaed92: SQL compilation error:
syntax error line 2 at position 0 unexpected ')'.
[SQL: 
CREATE TABLE "ROSSTURK"._tmp_jntrpgqnu65eaf3e1c94noiz1pd5gt70wlniesbnklb67i7eezkk9pxy1 (
)

]
```

**Expected behavior**
I think it should be possible to work with empty dataframes - both with this decorator and `aql.append()`.

**Comment by utkarsharma2** [comment]
@rossturk for creating this issue, We'll soon be back with the updates on this.

**Comment by pankajastro** [comment]
Does snowflake allow the creation of an empty table? I think `CREATE TABLE t ();` will not work in the case of the snowflake. In the case of an empty dataframe what is the table structure we are expecting here?

**Comment by pankajastro** [comment]
In the case of snowflake improve logging message @sunank200
