### ISSUE TITLE
aql.dataframe handles being given a dict/list/etc

### ISSUE THREAD

**Issue by rossturk** [astronomer/astro-sdk#811]
**Please describe the feature you'd like to see**

This one is a bit out there, but aql.dataframe does not behave well when the return value of the function it decorates is a list (or a dict or a string or whatever) instead of a dataframe.

**Describe the solution you'd like**
Perhaps the operator could attempt to convert it to a properly-dimensioned dataframe?

**Are there any alternatives to this feature?**
Yes. Instead of trying to convert it, the decorator could log an error saying that the return value needs to be a df.  

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by sunank200** [comment]
@rossturk Could you share one example use case, please?

**Comment by pankajastro** [comment]
Currently, the operator does raise an error when callable output is not a dataframe and we pass output_table param https://github.com/astronomer/astro-sdk/blob/main/python-sdk/src/astro/sql/operators/dataframe.py#L180 and if no output table pass it return the callable output

<img width="896" alt="Screenshot 2022-12-20 at 10 27 01 PM" src="https://user-images.githubusercontent.com/98807258/208722817-50e688d1-ead9-4df0-b2fe-5228ed99e70d.png">

**Comment by tatiana** [comment]
@rossturk How would you expect a list to be loaded into a dataframe? What should be the column name? What if the list was a "nested list"? Also, what would we expect the behaviour to be for nested dictionaries?

My gut feeling is that we should focus on giving a friendly error message to users saying that we don't support returning those filetypes - but I'm happy to be convinced otherwise :smile:

**Comment by pankajastro** [comment]
@rossturk Looking for your thoughts on the above^^

**Comment by pankajastro** [comment]
please re-open if needed. thank you.
