### ISSUE TITLE
Store Benchmarking results in a DB

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#822]
**Please describe the feature you'd like to see**
Currently, we store results in a GCS bucket.
via `gsutil cp $results_file gs://${GCP_BUCKET}/benchmark/results/`
But since we also would like to compare results it would be nice to save them in DB.

**Describe the solution you'd like**
Standardize the results and save them in DB

**Are there any alternatives to this feature?**
Open to suggestions

**Acceptance Criteria**

- [ ] There should be a table that at least has columns - dates of the run, dataset, location, duration, and memory consumption. 
- [ ] Benchmarking script should be modified to save data to the above-mentioned table.

**Comment by tatiana** [comment]
@utkarsharma2 aren't we sending the benchmark results to BQ as well ATM?
https://github.com/astronomer/astro-sdk/blob/main/python-sdk/tests/benchmark/run.py#L89

**Comment by phanikumv** [comment]
This may not be needed, let's test this and then close it if the functionality already exists.

**Comment by pankajkoti** [comment]
The results are exported to BQ and @sunank200 , @pankajkoti have tested this. Closing this.
