### ISSUE TITLE
 Analyze methods for integrating SQL CLI to Astro CLI

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#828]
**Please describe the feature you'd like to see**

As part of the SQL CLI 0.1, we need to make it available in the [Astro CLI](https://github.com/astronomer/astro-cli) project.

There are at least two known ways of achieving this:
* Override commands using the context feature
* Expose a full standalone subcommand

**Describe the solution you'd like**
We'd like to spike and understand these strategies and write a document with the pros and cons of each of them, proposing a path moving forward. We may want to consider a hybrid approach.

**Acceptance criteria**
* [x] Spike on integrating our CLI using these two strategies (PoCs)
* [x] An AEP similar to our [table cleanup proposal](https://github.com/astronomer/astro-sdk/blob/main/python-sdk/docs/aep/AEP-2-table-cleanup.md) documenting the pros and cons of each approach
* [x] Collect feedback from the Astro CLI team, since the decision of how to integrate to the Astro CLI should be taken in a shared manner
* [x] Have a decision on how we'll move forward.

**Comment by tatiana** [comment]
Created a document with the findings and shared it with the team:
https://docs.google.com/document/d/1q6PsaWzjPWYIyI6twdnJVs3MV5Je-uzby2UW9UjNYSE/edit#

Once there is an agreement, I'll be creating a PR so the analysis and decision is part of the repo.

**Comment by tatiana** [comment]
@tatiana please, add the final version to the Github repo

**Comment by kaxil** [comment]
Isn't this complete? What are the pending items on this one?

**Comment by tatiana** [comment]
Just created a PR, moving the Google Doc into an AEP, @kaxil :
https://github.com/astronomer/astro-sdk/pull/1126
