### ISSUE TITLE
Add `Run benchmarking` button on each Pull Request

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#831]
**Please describe the feature you'd like to see**
I really wish I could run benchmarking for each Pull Request that a contributor creates on the astro-sdk repo. This enables us to easily track which particular PR is impacting the performance of the operators.

**Describe the solution you'd like**
Add a label/button that lets a contributor trigger the benchmark process( and persist results in a database)

**Are there any alternatives to this feature?**
Run benchmarking process manually

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by phanikumv** [comment]
Lets re-visit this at a later point of time considering the time it takes to run benchmarking.

**Comment by utkarsharma2** [comment]
We have implemented this feature with the `run_benchmark` label.
