### ISSUE TITLE
Airflow with astro-python-sdk fails without `AIRFLOW__CORE__ENABLE_XCOM_PICKLING` env var

### ISSUE THREAD

**Issue by dimberman** [astronomer/astro-sdk#837]
**Describe the bug**
Users who install `astro-sdk-python` and do not set the `AIRFLOW__CORE__ENABLE_XCOM_PICKLING` env variable are unable to start up their webserver. They are getting an error as follows 

```
OSError: AIRFLOW__CORE__ENABLE_XCOM_PICKLING environment variable needs to be set to True or enable_xcom_pickling=true in airflow.cfg before importing astro-sdk-python.
```
This essentially makes airflow unusable unless they either uninstall the library or set the env var. This is an unoptimal experience for a library that should only affect DAGs that use it

**Version**
* Astro: [e.g. 0.6.0] 1.2.0
* OS: [eg. Debian]

**To Reproduce**
1. pip install the astro python sdk
2. don't set the `AIRFLOW__CORE__ENABLE_XCOM_PICKLING` env variable
3. Airflow will not start (the same can be found when running CLI commands like `airflow db init`

**Expected behavior**
This error should only fail at DAG parsing time, not at a global airflow level. DAGs with astro SDK should either fail parsing or fail at runtime (though ideally at parsing).

**Comment by phanikumv** [comment]
This should be closed as the airflow webserver is starting up well. The  tests are done as part of the below issue.

https://github.com/astronomer/astro-sdk/issues/1046

cc @kaxil
