### ISSUE TITLE
Fix duplicate load of data

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#838]
**Describe the bug**
In load_file() if the user has given a pattern that results in two files

example -
pattern : s3://tmp/

which results in files:

    s3://tmp/test1.csv
    s3://tmp/test2.csv

With the existing code and new autodetecting schema logic, we will end up with:

Step 1: Autoschema detect - Table + 1st file load
Step 2: Load data in a table - 1st file load + 2nd file load

will result in table 1 loading twice.

**Version**
* Astro: [e.g. 1.2.0]

**To Reproduce**
Load using a pattern and check the no. of rows.

**Expected behavior**
The number of rows should match with no. rows in files.

**Comment by pankajkoti** [comment]
PR is ready for review
