### ISSUE TITLE
Fix the issue with test_load_file_with_named_schema

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#849]
**Describe the bug**
The below test fails intermittently.

`FAILED tests/sql/operators/test_load_file.py::test_load_file_with_named_schema[csv-redshift]`

**Expected behavior**
The test should have constant behaviour.

**Comment by sunank200** [comment]
We don't have this test anymore.

**Comment by sunank200** [comment]
We don't have this test anymore.
