### ISSUE TITLE
Fix Filesupport and Autodetect mapping in databases

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#853]
**Describe the bug**
currently, the mapping in database/google/bigquery.py and database/snowflake.py implies that for every supported location(GCS/S3) we support all the filetypes - CVS/JSON, which is not accurate.

```
is_file_type_supported = (
    file.type.name in NATIVE_AUTODETECT_SCHEMA_SUPPORTED_FILE_TYPES
)
is_file_location_supported = (
    file.location.location_type
    in NATIVE_AUTODETECT_SCHEMA_SUPPORTED_FILE_LOCATIONS
)
return is_file_type_supported and is_file_location_supported
```

```
{
"GCS": [CSV, NDJSON],
"S3": [PARQUET]  # just an example. 
}
```

**Version**
* Astro: [e.g. 1.1.0b1]
* OS: [eg. Debian]

**Expected behavior**
It would be a good idea to check for location and then support fileType by that location
Mapping should be like:
```
NATIVE_AUTODETECT_SCHEMA_CONFIG: Mapping[
    FileLocation, Mapping[str, list[FileType] | Callable]
] = {
    FileLocation.GS: {
        "filetype": [FileType.CSV, FileType.NDJSON, FileType.PARQUET],
        "method": lambda table, file: None,
    }
}
```

**Comment by sunank200** [comment]
Its implemented as discussed.
