### ISSUE TITLE
Load `.data` file into a pandas dataframe from a url

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astro-sdk#881]
**Describe the bug**
I have a .data file I am trying to load into a pandas dataframe from a url. The file is basically a CSV format but has the .data extension.

**To Reproduce**
Example code
```
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"  # URL for Iris data API

dataframe = aql.load_file(
            input_file=File(path=data_url, filetype=FileType.CSV)
        )
```

**Expected behavior**
It should be able to load data in pandas dataframe

**Additional context**
error log

```
ValueError: Unsupported filetype 'data' from file 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'.
```

- [x] To add a test case covering this functionality

**Comment by phanikumv** [comment]
Ankit will start on this today
