### ISSUE TITLE
Move benchmarking config out of codebase to GCS

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#885]
**Please describe the feature you'd like to see**
Currently, we have config kept in the Codebase due to which whenever we want to modify it we have to generate a new docker image.

**Describe the solution you'd like**
We can move the config to GCS and load it from there. This way any mods to config won't affect the docker image.

**Are there any alternatives to this feature?**
Open to suggestions.

**Acceptance Criteria**

- [ ] While changing the config we should not generate a new docker image

**Comment by kaxil** [comment]
When would we ever want to change the "benchmark config"?

**Comment by sunank200** [comment]
It doesn't make sense to have the config both on github and GCS.

**Comment by phanikumv** [comment]
Closing this as discussed with the team that it is not required anymore
