### ISSUE TITLE
Issue with loading files using LoadFileOperator with native_support=True

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#890]
**Describe the bug**
Check why the `'use_native_support'=True` isn't loading all the files with the LoadFileOperator
Relevant thread https://astronomer.slack.com/archives/C02B8SPT93K/p1663783869151809
************

I'm seeing an issue in my job with the LoadFileOperator
The file was a GCS Parquet file - I physically checked and there is data in it
The table was a Snowflake TempTable - I checked and it's empty
It then gets merged with a MergeOperator, but given that the temp table was empty, nothing was added
No errors in the logs as far as I can tell.
I have use_native_support=True - should I turn it off and see if that helps?
This happened only occasionally - I loaded ~80 files each for 4 different tables (as fast as airflow could load them), and only some loads were affected
It does appear to happen consistently with the same records missing for at least one case if I rerun the tasks though
************

**Version**
* Astro: [e.g. 0.6.0]
* OS: [eg. Debian]

**To Reproduce**
1. Write the DAG  '...'
2. Create connection '....'
3. Run using  '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by utkarsharma2** [comment]
@fritz-astronomer I'm not able to reproduce this on my local, can you share the details like the GCS files and Snowflake Table details OR we can get on a call to try this out?

**Comment by fritz-astronomer** [comment]
@utkarsharma2 following up in slack

**Comment by utkarsharma2** [comment]
Need to try on the env @fritz-astronomer has shared with me.

**Comment by fritz-astronomer** [comment]
Thank you!!!!
