### ISSUE TITLE
Add support for Azure Blob Storage

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#905]

**Comment by luanmorenomaciel** [comment]
Any timeline by when this support is going to be added into the astro sdk>

**Comment by kaxil** [comment]
Hey, @luanmorenomaciel , in few months but we can prioritize if you have interest and planning to use SDK

**Comment by tatiana** [comment]
I just agreed with @luanmorenomaciel that the focus of this ticket would be to implement the Azure Blob Storage FileLocation & the non-native transfer.

We'll have separate tickets for addressing the native transfers.

**Comment by luanmorenomaciel** [comment]
starting to work on this item, narrowing the scope to send an small PR where we can list files from WASB and ABFSS protocol using the get_file_list operator

https://astro-sdk-python.readthedocs.io/en/stable/astro/files/operators/get_file_list.html

**Comment by phanikumv** [comment]
Hey @luanmorenomaciel - feel free to let us know if you need any help with the implementation

**Comment by luanmorenomaciel** [comment]
First PR submitted 
https://github.com/astronomer/astro-sdk/pull/1275
