### ISSUE TITLE
Execute astro-sdk integration tests on astro cloud

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#913]
**Please describe the feature you'd like to see**
Enable astro sdk  integration tests to run on astro cloud, similar to providers team integration tests.

**Describe the solution you'd like**
A clear and concise description of what you want to happen, if possible with code examples.

**Are there any alternatives to this feature?**
Is there another way we could solve this problem or enable this use-case?

**Additional context**
Add any other context about the feature request here.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by sunank200** [comment]
@kelechi2020 Can you please confirm that we are running the astro sdk integration tests on Astro-runtime?

**Comment by kelechi2020** [comment]
We are able to run the astro-sdk example dags on Astro-runtime.

**Comment by pankajastro** [comment]
> We are able to run the astro-sdk example dags on Astro-runtime.

How did you deploy it on astro, I mean do you have some automation script for deployment?

**Comment by pankajastro** [comment]
@kaxil Any thoughts on how we can run integration tests (not example DAG)?

**Comment by kaxil** [comment]
This ticket was more about running the Example DAGs on Astro Cloud similar to how we do those for astronomer-providers

**Comment by pankajastro** [comment]
We would need to run a Postgres instance to test examples related to Postgres where should we run that?

**Comment by phanikumv** [comment]
we can run it on azure or any cloud of your choice - consider adding a task containing a start up / shutdown script in order to not take up too much costs

**Comment by phanikumv** [comment]
Implementation is 50% done. @pankajastro to connect with @ash / @uranusjr and discuss regarding the postgres connection issue.

**Comment by sunank200** [comment]
As discussed @rajaths010494 would be fixing the merge example DAGs. He has figured out that the data is unavailable on astro-sdk local. @rajaths010494 can you add more details

**Comment by rajaths010494** [comment]
MWegw and append dags are working fine. Have setup postgres on azure need to run load files and other dags

**Comment by sunank200** [comment]
1. Databricks cluster not available - @rajaths010494 to connect with Daniel about this
2. Dataframe DAG failing - @sunank200  to pair with @rajaths010494 
3. Sqlite table not available for transform DAGs - @rajaths010494 to create a SQLite server and use it in connection
