### ISSUE TITLE
Disable the SDK from changing capitalization of output columns by default

### ISSUE THREAD

**Issue by pgzmnk** [astronomer/astro-sdk#917]
**Describe the bug**

Users expressed confusion on why the column names for output tables are lowercased. It's due to this [default setting](https://github.com/astronomer/astro-sdk/blob/main/python-sdk/src/astro/sql/operators/dataframe.py#L110). 

**Expected behavior**

The default behavior should be to not change casing and it should be configureable with a global variable.

That way we can avoid hardcoding this setting into the Astro Build dagfile generator script.

**Version**
1.1.0

**To Reproduce**
Run [this Pipeline](https://cloud.astronomer.io/cku7t3fvx59046554xr4g0siv7r/build/17982df9-c45f-43ec-b2dd-bfd6f42d1c8c/fd5d862c-bcad-4be2-a3a4-f7b3b9920bca).

**Screenshots**
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/27398253/192357157-e5c7b9d4-3517-4f5c-8521-0098375bc052.png">

**Additional context**
[Slack thread from September 26 2022](https://astronomer.slack.com/archives/C02B8SPT93K/p1664208204100329).

**Comment by kaxil** [comment]
Some related snowflake issues:
- https://github.com/snowflakedb/snowflake-sqlalchemy/issues/157
- https://github.com/apache/superset/issues/18085
