### ISSUE TITLE
Backport the new dag test feature to users using Airflow 2.1

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#931]
**Please describe the feature you'd like to see**

SQL SDK 0.1 users should be able to run the SQL workflows using the new implementation of `airflow dag test` (https://github.com/apache/airflow/pull/26400), even when they are using Airflow 2.1.

**Describe the solution you'd like**
Users using Airflow 2.5 and 2.1 should be able to run the SQL workflows the same way, using the new implementation of `airflow dag test`

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by tatiana** [comment]
@dimberman to help us spec'ing this work

**Comment by kaxil** [comment]
Can this be closed? or is it still WIP @tatiana @dimberman ?
