### ISSUE TITLE
CI execute some job twice if a label added in PR

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astro-sdk#948]
**Describe the bug**
Create a PR and add a label you can see couple jobs for `Markdown-link-check`

**Version**
* Astro: [e.g. 0.6.0]
* OS: [eg. Debian]

**To Reproduce**
1. Write the DAG  '...'
2. Create connection '....'
3. Run using  '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kaxil** [comment]
Closed by https://github.com/astronomer/astro-sdk/pull/928
