### ISSUE TITLE
Test End to End CI benchmarking

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#955]
We need to verify the end-to-end CI/Benchmarking is working.
1. Adding a label
2. Cron

**Comment by sunank200** [comment]
@utkarsharma2 did the cron job run successfully? If so we should update this ticket

**Comment by sunank200** [comment]
@utkarsharma2 to sync with @uranusjr to debug this

**Comment by utkarsharma2** [comment]
Test end to end with 10kb to 1gb files.
