### ISSUE TITLE
Support FTP / SFTP `File`s

### ISSUE THREAD

**Issue by fritz-astronomer** [astronomer/astro-sdk#969]
**Please describe the feature you'd like to see**
It is a very common ETL operation to either push data to or load data from FTP sources

**Describe the solution you'd like**
FTP + SFTP should be valid location types in `File`

**Are there any alternatives to this feature?**
Implementors otherwise need to use workarounds like `S3toSFTPOperator`

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by rajaths010494** [comment]
Hey @fritz-astronomer is there any specific use case for this?

**Comment by rajaths010494** [comment]
Hey @fritz-astronomer if you have any sample dag for FTP can you share it with me so that i can try out and see FTP /SFTP works as expected.

**Comment by fritz-astronomer** [comment]
[sftp_scratch.zip](https://github.com/astronomer/astro-sdk/files/10271005/sftp_scratch.zip)
