### ISSUE TITLE
Improve load_file  and save_file speed for bigquery

### ISSUE THREAD

**Issue by dimberman** [astronomer/astro-sdk#99]
During testing, we found that the load speed of dataframe -> postgres to be fairly slow. We believe that there should be a faster native way to load data into postgres.

Acceptance criteria:

A notable speed improvement on postgres load and save numbers in the load and save file
detailed instructions for users to add any needed extensions to their database that would enable these features (e.g. s3 support)

**Comment by tatiana** [comment]
We split this ticket into two new ones:
* https://github.com/astronomer/astro-sdk/issues/437
* https://github.com/astronomer/astro-sdk/issues/429
